import {useState} from 'react';
import {Alert,Pressable,Text,TextInput,View} from 'react-native';
import {useDepartments,useDepartmentEdit} from './useDepartments';
import type {Department} from './departmentAdminApi';
import {DepartmentCreation} from './DepartmentCreation';
type Props={base:string;token:string;companyId:string;branchId:string;canEdit:boolean;accent:string;onExpired:()=>void};
const note={color:'#8B99A8',marginVertical:8},input={color:'#F1F5F9',backgroundColor:'#0B1118',padding:12,borderRadius:12};
export function DepartmentsPanel(p:Props){const s=useDepartments(p.base,p.token,p.companyId,p.branchId,p.onExpired),[selected,setSelected]=useState<Department|null>(null);const close=()=>{setSelected(null);s.refresh();};const button=(label:string,fn:()=>void,disabled=false)=><Pressable accessibilityRole="button" disabled={disabled} onPress={fn}><Text style={{color:disabled?'#8B99A8':p.accent,paddingVertical:12}}>{label}</Text></Pressable>;
 return <View style={{backgroundColor:'#111923',padding:16,borderRadius:18,marginBottom:24}}><Text style={{color:'#F1F5F9',fontSize:20,fontWeight:'700'}}>Departamentos de tu sucursal</Text>{p.canEdit&&<DepartmentCreation {...p} disabled={false} onCreated={()=>s.refresh()}/>}<TextInput accessibilityLabel="Buscar nombre o código de departamento" maxLength={100} value={s.search} onChangeText={s.setSearch} style={input}/><View style={{flexDirection:'row',gap:12}}>{[['','Todos'],['ACTIVE','Activos'],['INACTIVE','Inactivos']].map(([value,label])=><Pressable key={value} accessibilityRole="button" accessibilityState={{selected:s.status===value}} onPress={()=>s.setStatus(value)}><Text style={{color:s.status===value?p.accent:'#8B99A8',paddingVertical:12}}>{label}</Text></Pressable>)}</View>{button('Buscar',s.apply,s.loading)}{s.loading&&<Text style={note}>Consultando…</Text>}{s.error&&<Text accessibilityRole="alert" style={{color:'#F87171'}}>{s.error}</Text>}{selected&&<Edit key={selected.id} {...p} row={selected} onClose={close}/>} {!s.loading&&!s.error&&!s.page.items.length&&<Text style={note}>No hay departamentos para esta búsqueda.</Text>}{s.page.items.map(row=><View key={row.id} style={{paddingVertical:12}}><Text style={{color:'#F1F5F9',fontWeight:'700'}}>{row.name}</Text><Text style={note}>{row.code} · {row.status==='ACTIVE'?'Activo':'Inactivo'}</Text>{p.canEdit&&button('Editar departamento',()=>setSelected({...row}),!!selected)}</View>)}<Text style={note}>Página {s.pageNumber} · Hasta 20 registros</Text>{button('Anterior',s.previous,s.loading||s.pageNumber===1)}{button('Siguiente',s.next,s.loading||!!s.error||!s.page.nextCursor)}{button('Actualizar departamentos',s.refresh,s.loading)}</View>;
}
function Edit({base,token,row,onClose,accent,onExpired}:Props&{row:Department;onClose:()=>void}){const s=useDepartmentEdit(base,token,row,onClose,onExpired),locked=s.busy||s.blocked;const button=(label:string,fn:()=>void,disabled=false)=><Pressable accessibilityRole="button" disabled={disabled} onPress={fn}><Text style={{color:disabled?'#8B99A8':accent,paddingVertical:12}}>{label}</Text></Pressable>;return <View><Text style={{color:'#F1F5F9',fontWeight:'700'}}>Editar {row.name}</Text><Text style={note}>Nombre</Text><TextInput accessibilityLabel="Editar nombre del departamento" editable={!locked} maxLength={120} value={s.name} onChangeText={s.setName} style={input}/><Text style={note}>Código</Text><TextInput accessibilityLabel="Editar código del departamento" editable={!locked} maxLength={32} value={s.code} onChangeText={s.setCode} style={input}/><View style={{flexDirection:'row',gap:12}}>{(['ACTIVE','INACTIVE'] as const).map(value=><Pressable key={value} disabled={locked} accessibilityRole="button" accessibilityState={{selected:s.status===value}} onPress={()=>s.setStatus(value)}><Text style={{color:s.status===value?accent:'#8B99A8',paddingVertical:12}}>{value==='ACTIVE'?'Activo':'Inactivo'}</Text></Pressable>)}</View><Text style={note}>Para desactivar, primero reasigna o desactiva sus empleados activos. Se conserva el historial.</Text>{s.error&&<Text accessibilityRole="alert" style={{color:'#F87171'}}>{s.error}</Text>}{button('Guardar departamento',()=>Alert.alert('Confirmar departamento',`${s.name.trim()} (${s.code.trim().toUpperCase()}) · ${s.status==='ACTIVE'?'Activo':'Inactivo'}`,[{text:'Cancelar',style:'cancel'},{text:'Guardar',onPress:()=>void s.save()}]),!s.ready)}{button('Cerrar y actualizar',onClose,s.busy)}</View>;}
