import {EmployeeDepartment} from './EmployeeDepartment';
import {EmployeeStatus} from './EmployeeStatus';
import {EmployeeEdit} from './EmployeeEdit';
import {EmployeeCreation} from './EmployeeCreation';
import {Pressable,Text,TextInput,View} from 'react-native';
import {useEmployees} from './useEmployees';
export function EmployeePanel({base,token,companyId,branchId,accent,onExpired,canCreate,canManageDepartments,canEdit}:{base:string;token:string;companyId:string;branchId:string;canCreate:boolean;canManageDepartments:boolean;canEdit:boolean;accent:string;onExpired:()=>void}){
 const s=useEmployees(base,token,companyId,branchId,onExpired);const note={color:'#8B99A8',marginVertical:8};const button=(label:string,fn:()=>void,disabled=false)=><Pressable accessibilityRole="button" disabled={disabled} onPress={fn}><Text style={{color:disabled?'#8B99A8':accent,paddingVertical:12}}>{label}</Text></Pressable>;
 return <View style={{backgroundColor:'#111923',borderRadius:18,padding:16,marginBottom:24}}><Text style={{color:'#F1F5F9',fontSize:20,fontWeight:'700'}}>Empleados de tu sucursal</Text>{canCreate&&<EmployeeCreation key={token} canManageDepartments={canManageDepartments} base={base} token={token} companyId={companyId} branchId={branchId} onSaved={s.refresh} accent={accent} onExpired={onExpired} />}<Text style={note}>Nombre o puesto</Text><TextInput accessibilityLabel="Buscar empleado por nombre o puesto" maxLength={100} value={s.search} onChangeText={s.setSearch} style={{color:'#F1F5F9',backgroundColor:'#0B1118',padding:12,borderRadius:12}}/><View style={{flexDirection:'row',gap:16}}>{[['','Todos'],['ACTIVE','Activos'],['INACTIVE','Inactivos']].map(([value,label])=><Pressable key={value} accessibilityRole="button" accessibilityState={{selected:s.status===value}} onPress={()=>s.setStatus(value)}><Text style={{color:s.status===value?accent:'#8B99A8',paddingVertical:12}}>{label}</Text></Pressable>)}</View>{button('Buscar',s.apply,s.loading)}{s.loading&&<Text style={note}>Consultando…</Text>}{s.error&&<Text accessibilityRole="alert" style={{color:'#F87171'}}>{s.error}</Text>}{!s.loading&&!s.error&&!s.page.items.length&&<Text style={note}>No hay empleados para esta consulta.</Text>}{s.page.items.map(row=><View key={row.id} style={{paddingVertical:12,borderBottomWidth:1,borderBottomColor:'#293746'}}><Text style={{color:'#F1F5F9'}}>{row.fullName}</Text><Text style={note}>{row.position} · {row.status==='ACTIVE'?'Activo':'Inactivo'}</Text><Text style={note}>Departamento: {row.departmentId}</Text>{canEdit&&<EmployeeEdit base={base} token={token} employee={row} onSaved={s.refresh} accent={accent} onExpired={onExpired} />}{canEdit&&<EmployeeStatus base={base} token={token} employee={row} onSaved={s.refresh} accent={accent} onExpired={onExpired} />}{canEdit&&<EmployeeDepartment base={base} token={token} employee={row} onSaved={s.refresh} accent={accent} onExpired={onExpired} />}</View>)}<Text style={note}>Página {s.pageNumber} · Hasta 20 empleados por página</Text>{button('Anterior',s.previous,s.loading||s.pageNumber===1)}{button('Siguiente',s.next,s.loading||!!s.error||!s.page.nextCursor)}{button('Actualizar',s.refresh,s.loading)}</View>;
}
