import {useState} from 'react';
import {Alert,Pressable,Text,TextInput,View} from 'react-native';
import type {Employee} from './employeeApi';
import {useEmployeeDepartment} from './useEmployeeDepartment';
type Props={base:string;token:string;employee:Employee;onSaved:()=>void;onExpired:()=>void;accent:string};
export function EmployeeDepartment(p:Props){const [open,setOpen]=useState(false);return open?<Form {...p} onClose={()=>{setOpen(false);p.onSaved();}}/>:<Pressable accessibilityRole="button" onPress={()=>setOpen(true)}><Text style={{color:p.accent,paddingVertical:12}}>Cambiar departamento</Text></Pressable>;}
function Form({base,token,employee,onSaved,onClose,onExpired,accent}:Props&{onClose:()=>void}){
 const s=useEmployeeDepartment(base,token,employee,onClose,onExpired),o=s.options,locked=s.busy||s.blocked;const note={color:'#8B99A8',marginVertical:8};
 const button=(label:string,fn:()=>void,disabled=false)=><Pressable accessibilityRole="button" disabled={disabled} onPress={fn}><Text style={{color:disabled?'#8B99A8':accent,paddingVertical:12}}>{label}</Text></Pressable>;
 return <View><Text style={{color:'#F1F5F9',fontWeight:'700'}}>Cambiar departamento de {s.original.fullName}</Text><Text style={note}>Departamento actual: {s.original.departmentId}</Text><TextInput accessibilityLabel="Buscar departamento activo" editable={!locked} maxLength={100} value={o.search} onChangeText={o.setSearch} style={{color:'#F1F5F9',backgroundColor:'#0B1118',padding:12,borderRadius:12}}/>{button('Buscar departamentos',o.apply,locked||o.loading)}{o.loading&&<Text style={note}>Consultando…</Text>}{o.error&&<Text accessibilityRole="alert" style={{color:'#F87171'}}>{o.error}</Text>}{!o.loading&&!o.error&&!o.items.length&&<Text style={note}>No hay departamentos activos para esta búsqueda.</Text>}{o.items.map(row=><Pressable key={row.id} accessibilityRole="radio" accessibilityState={{checked:o.selected?.id===row.id}} disabled={locked} onPress={()=>o.setSelected(row)}><Text style={{color:accent,paddingVertical:12}}>{o.selected?.id===row.id?'●':'○'} {row.name}{row.id===s.original.departmentId?' · Actual':''}</Text></Pressable>)}<Text style={note}>Seleccionado: {o.selected?.name??'Ninguno'} · Página {o.page}</Text>{button('Anterior',o.previous,locked||o.loading||o.page===1)}{button('Siguiente',o.next,locked||o.loading||!o.hasNext)}{s.error&&<Text accessibilityRole="alert" style={{color:'#F87171'}}>{s.error}</Text>}{button('Guardar departamento',()=>Alert.alert('Confirmar departamento',`${s.original.fullName} → ${o.selected?.name}`,[{text:'Cancelar',style:'cancel'},{text:'Guardar',onPress:()=>void s.save()}]),!s.ready)}{button('Cerrar y actualizar empleado',onClose,s.busy)}</View>;
}
