import { useEffect, useState } from 'react';
import { Pressable, Text, TextInput, View } from 'react-native';
import { ApiError } from './api';
import { financePage, type FinanceAccount, type CashEntry } from './financeApi';
export function FinancePageView({base,token,kind,accent,disabled=false,onExpired,onSelect,selected,activeOnly=false}: {base:string;token:string;kind:'bank-accounts'|'cash-movements';accent:string;disabled?:boolean;onExpired:()=>void;onSelect?:(row:FinanceAccount)=>void;selected?:FinanceAccount|null;activeOnly?:boolean}) {
 const [rows,setRows]=useState<(FinanceAccount|CashEntry)[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[applied,setApplied]=useState(''),[type,setType]=useState(''),[cursors,setCursors]=useState(['']),[next,setNext]=useState<string|null>(null),[revision,setRevision]=useState(0);
 const cursor=cursors[cursors.length-1],locked=loading||disabled;
 useEffect(()=>{const c=new AbortController();setLoading(true);setError('');setRows([]);setNext(null);financePage(base,token,kind,c.signal,applied,cursor,type,activeOnly?'ACTIVE':'').then(page=>{if(!c.signal.aborted){setRows(page.items);setNext(page.nextCursor);}}).catch(e=>{if(!c.signal.aborted){if(e instanceof ApiError&&e.status===401)onExpired();else setError(e instanceof Error?e.message:'No se pudo consultar.');}}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[base,token,kind,applied,cursor,type,revision,onExpired,activeOnly]);
 function button(label:string,blocked:boolean,run:()=>void){return <Pressable accessibilityRole="button" disabled={blocked} onPress={run}><Text style={{color:blocked?'#718096':accent,paddingVertical:12}}>{label}</Text></Pressable>;}
 return <View style={{backgroundColor:'#111923',borderRadius:18,padding:16,marginBottom:20}}>
 <Text style={{color:'#F1F5F9',fontSize:18,fontWeight:'700'}}>{kind==='bank-accounts'?'Cuentas de tu sucursal':'Movimientos de caja'}</Text>
 {selected?<Text style={{color:'#8B99A8'}}>Seleccionada: {selected.name}</Text>:null}
 <TextInput accessibilityLabel="Buscar registros financieros" editable={!disabled} maxLength={100} value={search} onChangeText={setSearch} placeholder={kind==='bank-accounts'?'Nombre, banco o identificador':'Concepto o fecha AAAA-MM-DD'} placeholderTextColor="#8B99A8" style={{backgroundColor:'#0B1119',color:'#F1F5F9',borderRadius:12,padding:12,marginVertical:8}}/>
 <View style={{flexDirection:'row',justifyContent:'space-between'}}>{button('Buscar',locked,()=>{setApplied(search.trim());setCursors(['']);setRevision(v=>v+1);})}{button('Ver todos',locked,()=>{setSearch('');setApplied('');setCursors(['']);setRevision(v=>v+1);})}</View>
 {kind==='cash-movements'?<View style={{flexDirection:'row',justifyContent:'space-between'}}>{['','INFLOW','OUTFLOW'].map(value=><Pressable key={value} disabled={disabled} onPress={()=>{setType(value);setCursors(['']);}}><Text style={{color:type===value?accent:'#8B99A8',paddingVertical:12}}>{value==='INFLOW'?'Entradas':value==='OUTFLOW'?'Salidas':'Todos'}</Text></Pressable>)}</View>:null}
 {loading?<Text style={{color:'#8B99A8'}}>Consultando…</Text>:error?<Text accessibilityRole="alert" style={{color:'#F87171'}}>{error}</Text>:<><Text style={{color:'#8B99A8'}}>Página {cursors.length} · {rows.length} registros</Text>{!rows.length?<Text style={{color:'#8B99A8'}}>No hay registros para esta búsqueda.</Text>:null}{rows.map(row=><View key={row.id} style={{paddingVertical:12,borderBottomWidth:1,borderBottomColor:'#293746'}}>{'name' in row?<><Text style={{color:'#F1F5F9'}}>{row.name} · {row.bankName}</Text><Text style={{color:'#8B99A8'}}>{row.status==='ACTIVE'?'Activa':'Inactiva'}</Text>{onSelect?button(selected?.id===row.id?'Seleccionada':'Seleccionar cuenta',disabled||row.status!=='ACTIVE',()=>onSelect(row)):null}</>:<><Text style={{color:'#F1F5F9'}}>{row.concept}</Text><Text style={{color:'#8B99A8'}}>{row.type==='INFLOW'?'Entrada':'Salida'} · {row.amount.toLocaleString('es-MX')} · {row.date}</Text></>}</View>)}</>}
 <View style={{flexDirection:'row',justifyContent:'space-between'}}>{button('Anterior',locked||cursors.length===1,()=>setCursors(v=>v.slice(0,-1)))}{button('Siguiente',locked||!next,()=>{if(next)setCursors(v=>[...v,next]);})}</View>{button(error?'Reintentar':'Actualizar',locked,()=>{setCursors(['']);setRevision(v=>v+1);})}
 </View>;
}
