import type {AssignableRole} from './userCreationApi';
import type {ComplianceControl} from './complianceApi';
import type {RiskRecord} from './riskApi';
import type {SupportTicket} from './ticketApi';
import type {ManagedAsset} from './assetApi';
import type {QualityInspection} from './qualityApi';
import type {MaintenanceOrder} from './maintenanceApi';
import type {Shipment} from './shipmentApi';
import type {Opportunity} from './opportunityApi';
import type {ExportDocument} from './exportDocument';
import type {Project} from './projectApi';
import type {ProductionOrder} from './productionApi';
const projectStates={ACTIVE:'Activo',PAUSED:'Pausado',CLOSED:'Cerrado'};
const productionStates={planned:'Planeada',running:'En producción',completed:'Completada',cancelled:'Cancelada'};
export function projectDocument(row:Project):ExportDocument{return {title:'Proyecto: '+row.name,company:row.companyId,branch:row.branchId,note:'Datos consultados del proyecto. Los nombres corresponden al catálogo actual. Identificador: '+row.id,columns:['Proyecto','Cliente','Estado','Inicio','Fin','Avance (%)'],rows:[[row.name,row.customerName??'Cliente no disponible',projectStates[row.status],row.startDate,row.endDate,row.progress]]};}
export function productionDocument(row:ProductionOrder):ExportDocument{return {title:'Orden de producción '+row.id,company:row.companyId,branch:row.branchId,note:'Orden: '+row.id+'. Planeación y entrada del producto terminado. Incluye insumos de la orden y sus movimientos de consumo; no incluye costos. Cantidades sin unidad informada. Los nombres corresponden al catálogo actual.',columns:['Producto','SKU','Estado','Cantidad planeada','Cantidad terminada','Almacén de entrada','Movimiento de entrada'],rows:[[row.productName??'Producto no disponible',row.productSku??'',productionStates[row.status],row.plannedQuantity,row.completedQuantity,row.completionWarehouseName??'',row.completionMovementId??''],...(row.materials??[]).map(m=>[m.productName??'Insumo no disponible','',m.movementId?'Insumo consumido':'Insumo planeado',m.quantity,m.movementId?m.quantity:0,m.warehouseName??'Almacén no disponible',m.movementId??''])]};}

export function opportunityDocument(row:Opportunity):ExportDocument{const stages={QUALIFICATION:'Calificación',PROPOSAL:'Propuesta',NEGOTIATION:'Negociación',CLOSED_WON:'Ganada',CLOSED_LOST:'Perdida'};return {title:'Oportunidad: '+row.name,company:row.companyId,branch:row.branchId,note:'Monto previsto, moneda no informada. No representa una venta ni un cobro. Los nombres corresponden al catálogo actual. Identificador: '+row.id,columns:['Oportunidad','Cliente','Etapa','Monto previsto'],rows:[[row.name,row.customerName??'Cliente no disponible',stages[row.stage],row.amount]]};}

export function shipmentDocument(row:Shipment):ExportDocument{const labels={PENDING:'Pendiente',IN_TRANSIT:'En tránsito',DELIVERED:'Entregado',CANCELLED:'Cancelado'};return {title:'Envío '+row.id,company:row.companyId,branch:row.branchId,note:'Seguimiento de entrega. No modifica existencias ni cobros. Venta: '+row.saleId+'. Nombres del catálogo actual.',columns:['Cliente','Destino','Fecha programada','Estado'],rows:[[row.customerName??'Cliente no disponible',row.destination,row.scheduledDate,labels[row.status]]]};}

export function maintenanceDocument(row:MaintenanceOrder):ExportDocument{const states={scheduled:'Programado',in_progress:'En curso',completed:'Terminado',cancelled:'Cancelado'};const priorities={low:'Baja',medium:'Media',high:'Alta'};return {title:'Orden de mantenimiento '+row.id,company:row.companyId,branch:row.branchId,note:'Orden registrada en la sucursal. Equipo identificado por nombre; no representa un registro del catálogo de activos. Sin costos ni consumo de repuestos en este documento.',columns:['Equipo','Trabajo','Fecha programada','Prioridad','Estado','Resultado'],rows:[[row.assetName,row.description,row.scheduledDate,priorities[row.priority],states[row.status],row.completionNote??'']]};}

export function qualityDocument(row:QualityInspection):ExportDocument{const states={scheduled:'Programada',in_progress:'En curso',completed:'Terminada',cancelled:'Cancelada'},results={pass:'Aprobado',watch:'Con observaciones',fail:'Rechazado'},priorities={low:'Baja',medium:'Media',high:'Alta'};return {title:'Inspección '+row.id,company:row.companyId,branch:row.branchId,note:'Inspección registrada. No modifica existencias y no representa una certificación externa.',columns:['Objeto revisado','Criterios','Fecha','Prioridad','Estado','Resultado','Observaciones'],rows:[[row.subject,row.criteria,row.inspectionDate,priorities[row.priority],states[row.status],row.result?results[row.result]:'',row.completionNote??'']]};}

export function assetDocument(row:ManagedAsset):ExportDocument{const states={operational:'Operativo',maintenance:'En mantenimiento',offline:'Fuera de servicio',retired:'Retirado'};return {title:'Activo: '+row.name,company:row.companyId,branch:row.branchId,note:'Registro operativo. No calcula depreciación ni valor contable. Identificador: '+row.id,columns:['Nombre','Código','Ubicación','Estado'],rows:[[row.name,row.code,row.location,states[row.status]]]};}

export function ticketDocument(row:SupportTicket):ExportDocument{const states={open:'Abierto',in_progress:'En curso',resolved:'Resuelto',cancelled:'Cancelado'},priorities={low:'Baja',medium:'Media',high:'Alta'};return {title:'Ticket '+row.id,company:row.companyId,branch:row.branchId,note:'Registro de soporte interno. La fecha objetivo no representa un SLA contratado.',columns:['Asunto','Descripción','Fecha objetivo','Prioridad','Estado','Resolución'],rows:[[row.subject,row.description,row.targetDate,priorities[row.priority],states[row.status],row.completionNote??'']]};}

export function riskDocument(row:RiskRecord):ExportDocument{const states={identified:'Identificado',mitigating:'En mitigación',closed:'Cerrado',dismissed:'Descartado'},levels={low:'Bajo',medium:'Medio',high:'Alto'};return {title:'Riesgo '+row.id,company:row.companyId,branch:row.branchId,note:'Evaluación cualitativa interna. No calcula exposición monetaria ni certifica cumplimiento.',columns:['Riesgo','Plan de mitigación','Fecha de revisión','Nivel','Estado','Conclusión'],rows:[[row.name,row.mitigationPlan,row.reviewDate,levels[row.level],states[row.status],row.completionNote??'']]};}

export function complianceDocument(row:ComplianceControl):ExportDocument{const states={pending:'Pendiente',reviewing:'En revisión',completed:'Revisado',cancelled:'Cancelado'},results={pass:'Conforme',watch:'Con observaciones',fail:'No conforme'},priorities={low:'Baja',medium:'Media',high:'Alta'};return {title:'Obligación '+row.id,company:row.companyId,branch:row.branchId,note:'Revisión interna registrada. No constituye certificación ni dictamen legal.',columns:['Obligación','Requisito','Fecha límite','Prioridad','Estado','Resultado','Evidencia'],rows:[[row.name,row.requirement,row.dueDate,priorities[row.priority],states[row.status],row.result?results[row.result]:'',row.evidenceNote??'']]};}

export function roleDocument(row:AssignableRole,companyId:string):ExportDocument{return {title:'Rol: '+row.name,company:companyId,branch:'Todas las sucursales de la empresa',note:'Permisos definidos en el rol. No modifica el acceso de usuarios. '+(row.isSystem?'Rol del sistema.':'Rol de la empresa.')+' Estado: '+(row.isActive===false?'Inactivo.':'Activo.'),columns:['Rol','Descripción','Permiso'],rows:row.permissions.map(permission=>[row.name,row.description,permission])};}
