import {ApiError,requestData} from './api';
export type Opportunity={id:string;companyId:string;branchId:string;customerId:string;customerName?:string;name:string;amount:number;stage:'QUALIFICATION'|'PROPOSAL'|'NEGOTIATION'|'CLOSED_WON'|'CLOSED_LOST';status:'OPEN'|'WON'|'LOST';updatedAt:string};
export async function opportunityPage(base:string,token:string,co:string,br:string,search:string,status:string,cursor?:string,signal?:AbortSignal){const q=new URLSearchParams({search:search.trim(),limit:'20'});if(status)q.set('status',status);if(cursor)q.set('cursor',cursor);const raw:any=await requestData(base,'/crm/opportunities/page?'+q,{headers:{Authorization:'Bearer '+token},signal});const fail=()=>new ApiError('No se pudo confirmar la página de oportunidades.');if(!raw||!Array.isArray(raw.items)||raw.items.length>20||!(raw.nextCursor===null||typeof raw.nextCursor==='string'))throw fail();let previous=cursor;for(const r of raw.items){if(!r||!/^[a-f0-9]{24}$/i.test(r.id)||r.companyId!==co||r.branchId!==br||typeof r.name!=='string'||!r.name.trim()||typeof r.amount!=='number'||!Number.isFinite(r.amount)||r.amount<=0||!['QUALIFICATION','PROPOSAL','NEGOTIATION','CLOSED_WON','CLOSED_LOST'].includes(r.stage)||r.status!==(r.stage==='CLOSED_WON'?'WON':r.stage==='CLOSED_LOST'?'LOST':'OPEN')||(status&&r.status!==status)||(r.customerName!==undefined&&typeof r.customerName!=='string')||typeof r.updatedAt!=='string'||!Number.isFinite(Date.parse(r.updatedAt))||(previous&&r.id>=previous))throw fail();previous=r.id;}if(raw.nextCursor!==null&&(raw.items.length!==20||raw.nextCursor!==raw.items[19].id))throw fail();return raw as {items:Opportunity[];nextCursor:string|null};}

export type OpportunityCustomer={id:string;name:string;companyId:string;branchId:string;status:'ACTIVE'};
export function opportunityAmount(text:string){if(!/^\d+(?:\.\d{1,2})?$/.test(text.trim()))return NaN;const n=Number(text);return n>=0.01&&n<=1e12?n:NaN;}
export async function opportunityCustomers(base:string,token:string,co:string,br:string,search:string,cursor?:string,signal?:AbortSignal){const q=new URLSearchParams({search:search.trim(),limit:'20'});if(cursor)q.set('cursor',cursor);const raw:any=await requestData(base,'/crm/opportunities/customer-options?'+q,{headers:{Authorization:'Bearer '+token},signal});const fail=()=>new ApiError('No se pudo confirmar el selector de clientes.');if(!raw||!Array.isArray(raw.items)||raw.items.length>20||!(raw.nextCursor===null||typeof raw.nextCursor==='string'))throw fail();let previous=cursor;for(const row of raw.items){if(!row||!/^[a-f0-9]{24}$/i.test(row.id)||typeof row.name!=='string'||!row.name.trim()||row.companyId!==co||row.branchId!==br||row.status!=='ACTIVE'||(previous&&row.id>=previous))throw fail();previous=row.id;}if(raw.nextCursor!==null&&(raw.items.length!==20||raw.nextCursor!==raw.items[19].id))throw fail();return raw as {items:OpportunityCustomer[];nextCursor:string|null};}

export async function saveOpportunity(base:string,token:string,co:string,br:string,input:{name:string;amount:string;customerId?:string;stage:Opportunity['stage']},original?:Opportunity,signal?:AbortSignal){
 const name=input.name.trim(),amount=opportunityAmount(input.amount);const stages=['QUALIFICATION','PROPOSAL','NEGOTIATION','CLOSED_WON','CLOSED_LOST'];
 if(original?(original.status!=='OPEN'||!stages.includes(input.stage)||input.stage===original.stage):(name.length<2||name.length>120||!Number.isFinite(amount)||!/^[a-f0-9]{24}$/i.test(input.customerId??'')))throw new ApiError('Revisa cliente, nombre, monto y etapa.',400);
 const body=original?{stage:input.stage,expectedStage:original.stage,expectedUpdatedAt:original.updatedAt}:{name,amount,customerId:input.customerId};
 const raw:any=await requestData(base,'/crm/opportunities'+(original?'/'+encodeURIComponent(original.id)+'/stage':''),{method:original?'PATCH':'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify(body),signal});
 const expectedStage=original?input.stage:'QUALIFICATION',expectedStatus=expectedStage==='CLOSED_WON'?'WON':expectedStage==='CLOSED_LOST'?'LOST':'OPEN';
 if(!raw||!/^[a-f0-9]{24}$/i.test(raw.id)||raw.companyId!==co||raw.branchId!==br||raw.customerId!==(original?.customerId??input.customerId)||raw.name!==(original?.name??name)||raw.amount!==(original?.amount??amount)||raw.stage!==expectedStage||raw.status!==expectedStatus||typeof raw.updatedAt!=='string'||!Number.isFinite(Date.parse(raw.updatedAt))||(original&&raw.id!==original.id))throw new ApiError('No se pudo confirmar la oportunidad. Cierra y consulta la lista antes de reintentar.');return raw as Opportunity;
}
