import {DocumentExportButtons} from './DocumentExportButtons';
import {useEffect,useState} from 'react';
import {Pressable,Text,View} from 'react-native';
import {ApiError} from './api';
import {reportRequest,type ReportType,type ReportPeriod,type PeriodReportData} from './reportApi';
const labels:Record<string,string>={total:'Ventas no canceladas',orders:'Operaciones',units:'Cantidad vendida',income:'Entradas de caja',expenses:'Salidas de caja',balance:'Flujo neto',incomeEntries:'Número de entradas',expenseEntries:'Número de salidas'};
export function PeriodReportPanel({base,token,companyId,branchId,accent,onExpired}:{base:string;token:string;companyId:string;branchId:string;accent:string;onExpired:()=>void}){
 const [type,setType]=useState<ReportType>('sales'),[period,setPeriod]=useState<ReportPeriod>('month'),[data,setData]=useState<PeriodReportData|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{const c=new AbortController();setData(null);setLoading(true);setError('');reportRequest(base,token,type,period,{companyId,branchId},c.signal).then(v=>{if(!c.signal.aborted)setData(v);}).catch(e=>{if(!c.signal.aborted){if(e instanceof ApiError&&e.status===401)onExpired();else setError(e instanceof Error?e.message:'No se pudo consultar.');}}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[base,token,companyId,branchId,type,period,revision]);
 return <View style={{backgroundColor:'#111923',padding:16,borderRadius:18,marginTop:16}}><Text style={{color:'#F1F5F9',fontSize:20,fontWeight:'700'}}>Reportes por periodo</Text><View style={{flexDirection:'row',flexWrap:'wrap'}}>{([['sales','Ventas'],['cash-flow','Flujo de caja']] as const).map(([id,label])=><Pressable key={id} accessibilityRole="button" accessibilityState={{selected:type===id}} onPress={()=>setType(id)}><Text style={{color:type===id?accent:'#8B99A8',padding:12}}>{label}</Text></Pressable>)}</View><Text style={{color:'#8B99A8'}}>Periodo actual en UTC</Text><View style={{flexDirection:'row',flexWrap:'wrap'}}>{([['day','Día'],['week','Semana desde lunes'],['month','Mes'],['quarter','Trimestre'],['year','Año']] as const).map(([id,label])=><Pressable key={id} accessibilityRole="button" accessibilityState={{selected:period===id}} onPress={()=>setPeriod(id)}><Text style={{color:period===id?accent:'#8B99A8',padding:12}}>{label}</Text></Pressable>)}</View>{loading?<Text style={{color:'#8B99A8'}}>Consultando…</Text>:error?<Text accessibilityRole="alert" style={{color:'#F87171'}}>{error}</Text>:data?<><Text style={{color:'#8B99A8'}}>{data.from} a {data.to} (UTC)</Text>{Object.entries(data.metrics).map(([k,v])=><Text key={k} style={{color:'#F1F5F9',marginTop:10}}>{labels[k]}: {v.toLocaleString('es-MX',{maximumFractionDigits:6})}</Text>)}<DocumentExportButtons key={type+period+data.from+revision} accent={accent} document={{title:type==='sales'?'Reporte de ventas':'Reporte de flujo de caja',company:companyId,branch:branchId,note:data.from+' a '+data.to+' (UTC). Ventas excluye canceladas. Moneda no informada; caja no representa utilidad ni saldo bancario.',columns:['Indicador','Valor'],rows:Object.entries(data.metrics).map(([key,value])=>[labels[key]??key,value])}}/></>:null}<Pressable accessibilityRole="button" disabled={loading} onPress={()=>setRevision(v=>v+1)}><Text style={{color:accent,paddingVertical:16}}>Actualizar</Text></Pressable><Text style={{color:'#8B99A8'}}>Ventas usa fecha de registro y excluye canceladas. Caja usa la fecha del movimiento. Moneda no informada; el flujo neto no representa utilidad ni saldo bancario.</Text></View>;
}
