import {ApiError,requestData} from './api';
export type ProductionMaterial={productId:string;warehouseId:string;quantity:number;consumedQuantity?:number;movementId?:string;productName?:string;warehouseName?:string};
export type ProductionOrder={id:string;companyId:string;branchId:string;productId:string;productName?:string;productSku?:string;completionWarehouseName?:string;plannedQuantity:number;completedQuantity:number;status:'planned'|'running'|'completed'|'cancelled';completionWarehouseId?:string;completionMovementId?:string;materials?:ProductionMaterial[];updatedAt?:string;costCurrency?:string;productionCost?:number;deliveries?:{cost?:number;quantity:number;warehouseId:string;warehouseName?:string;movementId:string;materials:ProductionMaterial[]}[]};
export type ProductionProduct={id:string;companyId:string;name:string;sku:string;status:'ACTIVE'};
const id=(v:unknown)=>typeof v==='string'&&/^[a-f0-9]{24}$/i.test(v);
export function productionQuantity(text:string){if(!/^\d+(?:\.\d{1,6})?$/.test(text.trim()))return NaN;const n=Number(text);return Number.isFinite(n)&&n>=0.000001&&n<=1e9?n:NaN;}
function valid(r:any,co:string,br:string):r is ProductionOrder{return !!r&&(r.costCurrency===undefined||(typeof r.costCurrency==='string'&&/^[A-Z]{3}$/.test(r.costCurrency)))&&(r.productionCost===undefined||(typeof r.productionCost==='number'&&Number.isFinite(r.productionCost)&&r.productionCost>=0&&r.productionCost<=1e12))&&(r.updatedAt===undefined||(typeof r.updatedAt==='string'&&Number.isFinite(Date.parse(r.updatedAt))))&&(r.deliveries===undefined||(Array.isArray(r.deliveries)&&r.deliveries.length<=50&&r.deliveries.every((d:any)=>!!d&&typeof d.quantity==='number'&&Number.isFinite(d.quantity)&&d.quantity>0&&id(d.warehouseId)&&id(d.movementId)&&(d.warehouseName===undefined||(typeof d.warehouseName==='string'&&d.warehouseName.length>0&&d.warehouseName.length<=100))&&Array.isArray(d.materials)&&d.materials.length<=20&&(d.cost===undefined||(typeof d.cost==='number'&&Number.isFinite(d.cost)&&d.cost>=0&&d.cost<=1e9&&!!r.costCurrency))&&d.materials.every((m:any)=>!!m&&id(m.productId)&&id(m.warehouseId)&&id(m.movementId)&&typeof m.quantity==='number'&&Number.isFinite(m.quantity)&&m.quantity>0))&&Math.round(r.deliveries.reduce((n:number,d:any)=>n+d.quantity,0)*1e6)===Math.round(r.completedQuantity*1e6)))&&(r.materials===undefined||(Array.isArray(r.materials)&&r.materials.length<=20&&new Set(r.materials.map((m:any)=>m?.productId+':'+m?.warehouseId)).size===r.materials.length&&r.materials.every((m:any)=>!!m&&id(m.productId)&&m.productId!==r.productId&&id(m.warehouseId)&&typeof m.quantity==='number'&&Number.isFinite(m.quantity)&&m.quantity>=0.000001&&m.quantity<=1e9&&Math.abs(m.quantity*1e6-Math.round(m.quantity*1e6))<0.001&&['productName','warehouseName'].every(k=>m[k]===undefined||(typeof m[k]==='string'&&m[k].trim().length>0&&m[k].length<=120))&&(m.consumedQuantity===undefined||(typeof m.consumedQuantity==='number'&&Number.isFinite(m.consumedQuantity)&&m.consumedQuantity>=0&&m.consumedQuantity<=m.quantity))&&(m.movementId===undefined||id(m.movementId))&&(r.status!=='completed'||id(m.movementId)))))&&['productName','productSku','completionWarehouseName'].every(k=>r[k]===undefined||(typeof r[k]==='string'&&r[k].trim().length>0&&r[k].length<=120))&&id(r.id)&&id(r.productId)&&r.companyId===co&&r.branchId===br&&typeof r.plannedQuantity==='number'&&Number.isFinite(r.plannedQuantity)&&r.plannedQuantity>=0.000001&&r.plannedQuantity<=1e9&&typeof r.completedQuantity==='number'&&Number.isFinite(r.completedQuantity)&&r.completedQuantity>=0&&r.completedQuantity<=r.plannedQuantity&&['planned','running','completed','cancelled'].includes(r.status)&&(r.status!=='completed'||r.completedQuantity===r.plannedQuantity);}
export async function productionPage(base:string,token:string,co:string,br:string,status:string,cursor?:string,signal?:AbortSignal){const q=new URLSearchParams({limit:'20'});if(status)q.set('status',status);if(cursor)q.set('cursor',cursor);const raw:any=await requestData(base,'/production/orders/page?'+q,{headers:{Authorization:'Bearer '+token},signal});const fail=()=>new ApiError('No se pudo confirmar la página de producción.');if(!raw||!Array.isArray(raw.items)||raw.items.length>20||!(raw.nextCursor===null||typeof raw.nextCursor==='string'))throw fail();let previous=cursor;for(const r of raw.items){if(!valid(r,co,br)||(status&&r.status!==status)||(previous&&r.id>=previous))throw fail();previous=r.id;}if(raw.nextCursor!==null&&(raw.items.length!==20||raw.nextCursor!==raw.items[19].id))throw fail();return raw as {items:ProductionOrder[];nextCursor:string|null};}
export async function productionProducts(base:string,token:string,co:string,search:string,cursor?:string,signal?:AbortSignal){const q=new URLSearchParams({limit:'20',search:search.trim()});if(cursor)q.set('cursor',cursor);const raw:any=await requestData(base,'/production/product-options?'+q,{headers:{Authorization:'Bearer '+token},signal});const fail=()=>new ApiError('No se pudo confirmar el selector de productos.');if(!raw||!Array.isArray(raw.items)||raw.items.length>20||!(raw.nextCursor===null||typeof raw.nextCursor==='string'))throw fail();let previous=cursor;for(const r of raw.items){if(!r||!id(r.id)||r.companyId!==co||r.status!=='ACTIVE'||typeof r.name!=='string'||!r.name.trim()||typeof r.sku!=='string'||(previous&&r.id>=previous))throw fail();previous=r.id;}if(raw.nextCursor!==null&&(raw.items.length!==20||raw.nextCursor!==raw.items[19].id))throw fail();return raw as {items:ProductionProduct[];nextCursor:string|null};}
export async function createProduction(base:string,token:string,co:string,br:string,productId:string,quantity:string,signal?:AbortSignal,materials:ProductionMaterial[]=[]){const n=productionQuantity(quantity);if(!valid({id:productId,companyId:co,branchId:br,productId,plannedQuantity:n,completedQuantity:0,status:'planned',materials},co,br))throw new ApiError('Revisa los insumos: máximo 20, cantidades positivas y sin duplicados.',400);if(!id(productId)||!Number.isFinite(n))throw new ApiError('Selecciona un producto y una cantidad positiva con hasta seis decimales.',400);const raw:any=await requestData(base,'/production/orders',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({productId,plannedQuantity:n,materials:materials.map(({productId,warehouseId,quantity})=>({productId,warehouseId,quantity}))}),signal});if(!valid(raw,co,br)||raw.productId!==productId||raw.plannedQuantity!==n||raw.completedQuantity!==0||raw.status!=='planned'||JSON.stringify((raw.materials??[]).map(({productId,warehouseId,quantity}:ProductionMaterial)=>({productId,warehouseId,quantity})))!==JSON.stringify(materials.map(({productId,warehouseId,quantity})=>({productId,warehouseId,quantity}))))throw new ApiError('No se pudo confirmar el alta. Consulta las órdenes antes de reintentar.');return raw;}
export async function productionAction(base:string,token:string,row:ProductionOrder,status:'running'|'cancelled'|'completed',warehouseId?:string,signal?:AbortSignal,deliveredQuantity?:number,cost?:{amount:number;currency:string}){
 const complete=status==='completed';
 if(!['planned','running'].includes(row.status)||(status==='running'&&row.status!=='planned')||(complete&&(row.status!=='running'||!id(warehouseId))))throw new ApiError('Revisa el estado y almacén de la orden.',400);
 const progress=Math.round((row.completedQuantity+(deliveredQuantity??row.plannedQuantity))*1e6)/1e6;
 const resultStatus=complete&&progress<row.plannedQuantity?'running':status;
 if(deliveredQuantity!==undefined&&(!complete||!Number.isFinite(deliveredQuantity)||Math.abs(deliveredQuantity*1e6-Math.round(deliveredQuantity*1e6))>=0.001||deliveredQuantity<=0||progress>row.plannedQuantity||!row.updatedAt))throw new ApiError('Revisa la cantidad entregada y actualiza la orden.',400);
 if(cost&&(!complete||!Number.isFinite(cost.amount)||cost.amount<0||cost.amount>1e9||Math.abs(cost.amount*100-Math.round(cost.amount*100))>=0.001||!/^[A-Z]{3}$/.test(cost.currency)||(row.costCurrency&&row.costCurrency!==cost.currency)))throw new ApiError('Revisa el costo y la moneda de esta entrega.',400);
 const payload=complete?{warehouseId,expectedQuantity:row.plannedQuantity,...(cost?{cost:cost.amount,currency:cost.currency}:{}),...(deliveredQuantity===undefined?{}:{deliveredQuantity,expectedCompletedQuantity:row.completedQuantity,expectedUpdatedAt:row.updatedAt})}:{expectedStatus:row.status,status};
 let raw:any;
 try{raw=await requestData(base,'/production/orders/'+row.id+(complete?'/complete':'/state'),{method:complete?'POST':'PATCH',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify(payload),signal});}
 catch(e){if(e instanceof ApiError&&e.status===409)throw new ApiError('La orden cambió. Actualiza y revisa Inventario antes de reintentar.',409);throw e;}
 const fail=()=>new ApiError('No se pudo confirmar la operación. Consulta la orden y el historial de Inventario antes de reintentar.');
 if(!valid(raw,row.companyId,row.branchId))throw fail();
 const recipe=(v:ProductionMaterial[]|undefined)=>JSON.stringify((v??[]).map(m=>[m.productId,m.warehouseId,m.quantity]).sort());
 const history=(v:ProductionOrder['deliveries'])=>JSON.stringify((v??[]).map(d=>[d.quantity,d.warehouseId,d.movementId,d.cost,d.materials.map(m=>[m.productId,m.warehouseId,m.quantity,m.movementId])]));
 if(recipe(raw.materials)!==recipe(row.materials)||raw.id!==row.id||raw.productId!==row.productId||raw.plannedQuantity!==row.plannedQuantity||raw.status!==resultStatus||raw.completedQuantity!==(complete?progress:0))throw fail();
 if(complete&&(raw.completionWarehouseId!==warehouseId||!id(raw.completionMovementId)))throw fail();
 if(complete&&deliveredQuantity!==undefined){const last=raw.deliveries?.[raw.deliveries.length-1];if(!raw.updatedAt||Date.parse(raw.updatedAt)<=Date.parse(row.updatedAt!)||!last||raw.deliveries!.length!==(row.deliveries?.length??0)+1||last.quantity!==deliveredQuantity||last.warehouseId!==warehouseId||last.movementId!==raw.completionMovementId||history(raw.deliveries!.slice(0,-1))!==history(row.deliveries))throw fail();}
 if(cost&&(raw.costCurrency!==cost.currency||Math.round((raw.productionCost??0)*100)!==Math.round((row.productionCost??0)*100)+Math.round(cost.amount*100)||raw.deliveries?.[raw.deliveries.length-1]?.cost!==cost.amount))throw fail();
 return raw;
}
