import {useEffect,useState} from 'react';
import {Pressable,Text,View} from 'react-native';
import {ApiError} from './api';
import {receiptRequest,type CommercialReceipt} from './settlementApi';
import type {Transaction,TransactionKind} from './transactionApi';
export function ReceiptView({base,token,kind,row,companyId,branchId,accent,onExpired,onClose}:{base:string;token:string;kind:TransactionKind;row:Transaction;companyId:string;branchId:string;accent:string;onExpired:()=>void;onClose:()=>void}){
 const [data,setData]=useState<CommercialReceipt|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0);
 useEffect(()=>{const c=new AbortController();setLoading(true);setError('');setData(null);receiptRequest(base,token,kind,row,{companyId,branchId},c.signal).then(v=>{if(!c.signal.aborted)setData(v);}).catch(e=>{if(!c.signal.aborted){if(e instanceof ApiError&&e.status===401)onExpired();else setError(e instanceof ApiError&&e.status===404?'Este documento no tiene comprobante de operación conjunta. Puede haberse cambiado de estado manualmente.':e.message);}}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[base,token,kind,row,companyId,branchId,revision]);
 const labels:Record<string,string>={id:'Comprobante',warehouseId:'Almacén',accountId:'Cuenta',stockMovementId:'Movimiento de inventario',cashMovementId:'Movimiento de caja',date:'Fecha de caja',quantity:'Cantidad',total:'Importe (moneda no informada)',status:'Estado'};
 return <View style={{backgroundColor:'#111923',padding:16,borderRadius:18}}><Text style={{color:'#F1F5F9',fontSize:20,fontWeight:'700'}}>Comprobante de operación conjunta</Text><Text selectable style={{color:'#8B99A8'}}>Documento: {row.id}</Text>{loading?<Text style={{color:'#8B99A8'}}>Consultando…</Text>:error?<Text accessibilityRole="alert" style={{color:'#F87171'}}>{error}</Text>:data&&Object.entries(data).map(([k,v])=><Text selectable key={k} style={{color:'#F1F5F9',marginTop:12}}>{labels[k]}: {v}</Text>)}<Pressable accessibilityRole="button" disabled={loading} onPress={()=>setRevision(v=>v+1)}><Text style={{color:accent,paddingVertical:16}}>Actualizar comprobante</Text></Pressable><Pressable accessibilityRole="button" onPress={onClose}><Text style={{color:accent,paddingVertical:16}}>Cerrar comprobante</Text></Pressable></View>;
}
