import {ApiError,requestData} from './api';
import type {AssignableRole} from './userCreationApi';

export function validRoleDraft(name:string,description:string,selected:string[],actor:string[]){return name.trim().length>=2&&name.trim().length<=60&&description.trim().length>=2&&description.trim().length<=250&&selected.length>=1&&selected.length<=100&&new Set(selected).size===selected.length&&selected.every(p=>actor.includes(p)&&/^[a-z][a-z0-9_-]*\.[a-z][a-z0-9_-]*$/i.test(p));}
export async function saveRole(base:string,token:string,co:string,name:string,description:string,selected:string[],actor:string[],signal?:AbortSignal){if(!validRoleDraft(name,description,selected,actor))throw new ApiError('Revisa nombre, descripción y permisos.',400);const body={name:name.trim().toUpperCase(),description:description.trim(),permissions:[...selected].sort()};const raw:any=await requestData(base,'/roles',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify(body),signal});if(!raw||!/^[a-f0-9]{24}$/i.test(raw.id)||raw.companyId!==co||raw.isSystem!==false||raw.name!==body.name||raw.description!==body.description||!Array.isArray(raw.permissions)||raw.permissions.length!==body.permissions.length||JSON.stringify([...raw.permissions].sort())!==JSON.stringify(body.permissions))throw new ApiError('No se pudo confirmar el rol. Actualiza antes de crearlo de nuevo.');return raw as AssignableRole;}

export async function saveRoleChange(base:string,token:string,co:string,original:AssignableRole,description:string,permissions:string[],actor:string[],signal?:AbortSignal){if(original.isActive===false||original.isSystem||original.companyId!==co||!original.updatedAt||!Number.isFinite(Date.parse(original.updatedAt))||!validRoleDraft(original.name,description,permissions,actor))throw new ApiError('Selecciona un rol de empresa válido y revisa sus permisos.',400);const body={description:description.trim(),permissions:[...permissions].sort(),expectedUpdatedAt:original.updatedAt};const raw:any=await requestData(base,'/roles/'+encodeURIComponent(original.id),{method:'PATCH',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify(body),signal});if(!raw||raw.id!==original.id||raw.name!==original.name||raw.companyId!==co||raw.isSystem!==false||raw.description!==body.description||!Array.isArray(raw.permissions)||JSON.stringify([...raw.permissions].sort())!==JSON.stringify(body.permissions)||typeof raw.updatedAt!=='string'||!Number.isFinite(Date.parse(raw.updatedAt)))throw new ApiError('No se pudo confirmar el cambio. Actualiza antes de reintentar.');return raw as AssignableRole;}

export async function saveRoleStatus(base:string,token:string,co:string,original:AssignableRole,actor:string[],signal?:AbortSignal){
 if(original.isSystem||original.companyId!==co||!original.updatedAt||!Number.isFinite(Date.parse(original.updatedAt))||original.permissions.some(p=>!actor.includes(p)))throw new ApiError('Selecciona un rol de empresa que puedas administrar.',400);
 const isActive=original.isActive===false;
 const raw:any=await requestData(base,'/roles/'+encodeURIComponent(original.id)+'/status',{method:'PATCH',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({isActive,expectedUpdatedAt:original.updatedAt}),signal});
 if(!raw||raw.id!==original.id||raw.companyId!==co||raw.isSystem!==false||raw.name!==original.name||raw.isActive!==isActive||raw.description!==original.description||!Array.isArray(raw.permissions)||JSON.stringify([...raw.permissions].sort())!==JSON.stringify([...original.permissions].sort())||typeof raw.updatedAt!=='string'||!Number.isFinite(Date.parse(raw.updatedAt))||Date.parse(raw.updatedAt)<=Date.parse(original.updatedAt))throw new ApiError('No se pudo confirmar el estado. Actualiza antes de reintentar.');
 return raw as AssignableRole;
}

export type RolePage={items:AssignableRole[];page:number;limit:number;total:number;totalPages:number};
export async function loadRolePage(base:string,token:string,co:string,actor:string[],page:number,search:string,signal?:AbortSignal):Promise<RolePage>{
 if(!Number.isInteger(page)||page<1||page>100000||search.trim().length>100)throw new ApiError('Revisa la búsqueda de roles.',400);
 const raw:any=await requestData(base,'/roles/page?page='+page+'&limit=20&search='+encodeURIComponent(search.trim()),{headers:{Authorization:'Bearer '+token},signal});
 if(!raw||raw.page!==page||raw.limit!==20||!Number.isSafeInteger(raw.total)||raw.total<0||raw.totalPages!==Math.max(1,Math.ceil(raw.total/20))||!Array.isArray(raw.items)||raw.items.length>20||raw.items.length>raw.total)throw new ApiError('No se pudo confirmar la página de roles.');
 const ids=new Set<string>();for(const r of raw.items){if(!r||typeof r.id!=='string'||!r.id||ids.has(r.id)||typeof r.name!=='string'||typeof r.description!=='string'||typeof r.isSystem!=='boolean'||typeof r.isActive!=='boolean'||(r.isSystem?r.companyId!==undefined:r.companyId!==co)||!Array.isArray(r.permissions)||r.permissions.some((p:unknown)=>typeof p!=='string'||!actor.includes(p))||(!r.isSystem&&(typeof r.updatedAt!=='string'||!Number.isFinite(Date.parse(r.updatedAt)))))throw new ApiError('No se pudo confirmar la página de roles.');ids.add(r.id);}
 return raw;
}
