import {useEffect,useRef,useState} from 'react';
import {Alert,Pressable,Text,TextInput,View} from 'react-native';
import {ApiError} from './api';
import {WarehouseSelector} from './WarehouseSelector';
import {FinancePageView} from './FinancePageView';
import type {WarehouseEntry} from './inventoryApi';
import type {FinanceAccount} from './financeApi';
import type {Transaction,TransactionKind} from './transactionApi';
import {settlementRequest} from './settlementApi';
export function SettlementForm({base,token,kind,row,companyId,branchId,accent,onExpired,onDone,onCancel}:{base:string;token:string;kind:TransactionKind;row:Transaction;companyId:string;branchId:string;accent:string;onExpired:()=>void;onDone:(id:string)=>void;onCancel:()=>void}){
 const [warehouse,setWarehouse]=useState<WarehouseEntry|null>(null),[account,setAccount]=useState<FinanceAccount|null>(null),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[saving,setSaving]=useState(false),[error,setError]=useState('');const write=useRef<AbortController|null>(null),mounted=useRef(true);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;write.current?.abort();};},[]);
 async function save(){if(!mounted.current||write.current||!warehouse||!account)return;const c=new AbortController();write.current=c;setSaving(true);setError('');try{const id=await settlementRequest(base,token,kind,row,{warehouseId:warehouse.id,accountId:account.id,date},{companyId,branchId},c.signal);if(!c.signal.aborted)onDone(id);}catch(e){if(!c.signal.aborted){if(e instanceof ApiError&&e.status===401)onExpired();else setError(e instanceof Error?e.message:'No se pudo confirmar.');}}finally{write.current=null;if(!c.signal.aborted)setSaving(false);}}
 function confirm(){if(saving||!warehouse||!account)return;Alert.alert(kind==='sales'?'Cobrar y entregar':'Recibir y pagar',`Documento: ${row.id}\nCantidad: ${row.quantity}\nImporte: ${row.total} (moneda no informada)\nAlmacén: ${warehouse.name}\nCuenta: ${account.name}\nFecha: ${date}\nSe registra inventario y caja juntos. Confirma que no has registrado manualmente estos movimientos.`,[{text:'Cancelar',style:'cancel'},{text:'Registrar',onPress:()=>void save()}]);}
 return <View style={{backgroundColor:'#111923',padding:16,borderRadius:18}}><Text style={{color:'#F1F5F9',fontSize:20,fontWeight:'700'}}>{kind==='sales'?'Cobrar y entregar':'Recibir y pagar'}</Text><Text style={{color:'#8B99A8'}}>Documento: {row.id} · Cantidad: {row.quantity} · Total: {row.total}</Text><Text style={{color:'#F1F5F9',marginTop:16}}>Almacén activo</Text><WarehouseSelector base={base} token={token} selected={warehouse} disabled={saving} accent={accent} onSelect={setWarehouse} onExpired={onExpired}/><FinancePageView base={base} token={token} kind="bank-accounts" accent={accent} disabled={saving} onExpired={onExpired} onSelect={setAccount} selected={account} activeOnly/><Text style={{color:'#8B99A8'}}>Fecha de caja (AAAA-MM-DD)</Text><TextInput accessibilityLabel="Fecha de caja de operación conjunta" editable={!saving} maxLength={10} value={date} onChangeText={setDate} style={{color:'#F1F5F9',backgroundColor:'#0B1119',padding:12,borderRadius:12}}/>{error?<Text accessibilityRole="alert" style={{color:'#F87171'}}>{error}</Text>:null}<Pressable accessibilityRole="button" disabled={saving||!warehouse||!account} onPress={confirm}><Text style={{color:accent,paddingVertical:16}}>{saving?'Registrando…':'Revisar y registrar operación conjunta'}</Text></Pressable><Pressable accessibilityRole="button" disabled={saving} onPress={onCancel}><Text style={{color:accent,paddingVertical:16}}>Cancelar</Text></Pressable></View>;
}
