import {ApiError,requestData} from './api';
export type Shipment={id:string;companyId:string;branchId:string;saleId:string;customerName?:string;destination:string;scheduledDate:string;status:'PENDING'|'IN_TRANSIT'|'DELIVERED'|'CANCELLED';updatedAt:string};
const date=(v:unknown)=>{if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v))return false;const d=new Date(v+'T00:00:00Z');return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===v;};
function valid(r:any,co:string,br:string):r is Shipment{return !!r&&/^[a-f0-9]{24}$/i.test(r.id)&&/^[a-f0-9]{24}$/i.test(r.saleId)&&r.companyId===co&&r.branchId===br&&typeof r.destination==='string'&&r.destination.trim().length>=3&&r.destination.length<=300&&date(r.scheduledDate)&&['PENDING','IN_TRANSIT','DELIVERED','CANCELLED'].includes(r.status)&&(r.customerName===undefined||typeof r.customerName==='string')&&typeof r.updatedAt==='string'&&Number.isFinite(Date.parse(r.updatedAt));}
export async function shipmentPage(base:string,token:string,co:string,br:string,search:string,status:string,cursor?:string,signal?:AbortSignal){const q=new URLSearchParams({search:search.trim(),limit:'20'});if(status)q.set('status',status);if(cursor)q.set('cursor',cursor);const raw:any=await requestData(base,'/shipments/page?'+q,{headers:{Authorization:'Bearer '+token},signal});const fail=()=>new ApiError('No se pudo confirmar la página de envíos.');if(!raw||!Array.isArray(raw.items)||raw.items.length>20||!(raw.nextCursor===null||typeof raw.nextCursor==='string'))throw fail();let previous=cursor;for(const r of raw.items){if(!valid(r,co,br)||(status&&r.status!==status)||(previous&&r.id>=previous))throw fail();previous=r.id;}if(raw.nextCursor!==null&&(raw.items.length!==20||raw.nextCursor!==raw.items[19].id))throw fail();return raw as {items:Shipment[];nextCursor:string|null};}
export type ShipmentSale={id:string;companyId:string;branchId:string;customerId:string;customerName:string;total:number;status:'PENDIENTE'|'PAGADA';createdAt:string};
export async function shipmentSales(base:string,token:string,co:string,br:string,cursor?:string,signal?:AbortSignal){
 const q=new URLSearchParams({limit:'20'});if(cursor)q.set('cursor',cursor);const raw:any=await requestData(base,'/shipments/sale-options?'+q,{headers:{Authorization:'Bearer '+token},signal});
 if(!raw||!Array.isArray(raw.items)||raw.items.length>20||!(raw.nextCursor===null||typeof raw.nextCursor==='string'))throw new ApiError('No se pudo confirmar la lista de ventas.');let previous=cursor;
 for(const r of raw.items){if(!r||!/^[a-f0-9]{24}$/i.test(r.id)||r.companyId!==co||r.branchId!==br||!['PENDIENTE','PAGADA'].includes(r.status)||typeof r.customerName!=='string'||typeof r.total!=='number'||!Number.isFinite(r.total)||r.total<0||(previous&&r.id>=previous))throw new ApiError('No se pudo confirmar la venta.');previous=r.id;}
 if(raw.nextCursor!==null&&(raw.items.length!==20||raw.nextCursor!==raw.items[19].id))throw new ApiError('No se pudo confirmar la página de ventas.');return raw as {items:ShipmentSale[];nextCursor:string|null};
}

export async function saveShipment(base:string,token:string,co:string,br:string,input:{saleId?:string;destination:string;scheduledDate:string;status:Shipment['status']},original?:Shipment,signal?:AbortSignal){const destination=input.destination.trim();if(original?(!['PENDING','IN_TRANSIT'].includes(original.status)||!(input.status==='CANCELLED'||original.status==='PENDING'&&input.status==='IN_TRANSIT'||original.status==='IN_TRANSIT'&&input.status==='DELIVERED')):(!/^[a-f0-9]{24}$/i.test(input.saleId??'')||destination.length<3||destination.length>300||!date(input.scheduledDate)))throw new ApiError('Revisa venta, destino, fecha y estado.',400);
 const body=original?{status:input.status,expectedStatus:original.status,expectedUpdatedAt:original.updatedAt}:{saleId:input.saleId,destination,scheduledDate:input.scheduledDate};const raw:any=await requestData(base,'/shipments'+(original?'/'+encodeURIComponent(original.id)+'/status':''),{method:original?'PATCH':'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify(body),signal});if(!valid(raw,co,br)||raw.saleId!==(original?.saleId??input.saleId)||raw.destination!==(original?.destination??destination)||raw.scheduledDate!==(original?.scheduledDate??input.scheduledDate)||raw.status!==(original?input.status:'PENDING')||(original&&raw.id!==original.id))throw new ApiError('No se pudo confirmar el envío. Cierra y consulta antes de reintentar.');return raw;}
