import {useEffect,useRef,useState} from 'react';
import {ApiError} from './api';
import {inventoryAlerts,inventoryPreference,saveInventoryPreference,type AlertPage,type InventoryPreference} from './inventoryPreferencesApi';
export function useInventoryAlerts(base:string,token:string,companyId:string,canConfigure:boolean,canEdit:boolean,onExpired?:()=>void){
 const [page,setPage]=useState<AlertPage|null>(null),[preference,setPreference]=useState<InventoryPreference|null>(null),[threshold,setThreshold]=useState(''),[search,setSearch]=useState(''),[applied,setApplied]=useState(''),[cursors,setCursors]=useState(['']),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[preferenceError,setPreferenceError]=useState(''),[notice,setNotice]=useState(''),[revision,setRevision]=useState(0);
 const write=useRef<AbortController|null>(null),mounted=useRef(true);const cursor=cursors[cursors.length-1];
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;write.current?.abort();};},[]);
 useEffect(()=>{const c=new AbortController();setLoading(true);setPage(null);setError('');setPreferenceError('');Promise.allSettled([inventoryAlerts(base,token,c.signal,applied,cursor),canConfigure?inventoryPreference(base,token,companyId,c.signal):Promise.resolve(null)]).then(([a,p])=>{if(c.signal.aborted)return;for(const result of [a,p])if(result.status==='rejected'&&result.reason instanceof ApiError&&result.reason.status===401)onExpired?.();if(a.status==='fulfilled')setPage(a.value);else setError(a.reason instanceof Error?a.reason.message:'No se pudieron consultar avisos.');if(p.status==='fulfilled'){setPreference(p.value);setThreshold(p.value?.threshold===null||p.value===null?'':String(p.value.threshold));}else setPreferenceError(p.reason instanceof Error?p.reason.message:'No se pudo consultar el ajuste.');setLoading(false);});return()=>c.abort();},[base,token,companyId,canConfigure,applied,cursor,revision]);
 function refresh(){if(saving)return;setCursors(['']);setRevision(v=>v+1);}
 async function save(){if(!mounted.current||write.current||!canConfigure||!canEdit||loading||preferenceError)return;const c=new AbortController();write.current=c;setSaving(true);setNotice('');setPreferenceError('');try{const saved=await saveInventoryPreference(base,token,companyId,preference?.version??null,threshold,c.signal);if(!c.signal.aborted){setPreference(saved);setNotice('Umbral confirmado.');setCursors(['']);setRevision(v=>v+1);}}catch(e){if(!c.signal.aborted){if(e instanceof ApiError&&e.status===401)onExpired?.();setPreferenceError((e instanceof Error?e.message:'No se pudo confirmar.')+' Actualiza antes de volver a guardar.');}}finally{write.current=null;if(!c.signal.aborted)setSaving(false);}}
 return {page,threshold,setThreshold,search,setSearch,loading,saving,error,preferenceError,notice,save,refresh,pageNumber:cursors.length,searchNow:()=>{if(!saving){setApplied(search.trim());setCursors(['']);setRevision(v=>v+1);}},previous:()=>setCursors(v=>v.slice(0,-1)),next:()=>{if(page?.nextCursor)setCursors(v=>[...v,page.nextCursor!]);}};
}
