import {useEffect,useRef,useState} from 'react';
import {ApiError} from './api';
import {loadCompany,loadBranches,saveCompany,saveBranch,validBranch,type CompanyInfo,type BranchInfo,type BranchDraft} from './organizationApi';
export function useOrganization(base:string,token:string,co:string,onExpired?:()=>void){
 const [companyError,setCompanyError]=useState(''),[companyLoading,setCompanyLoading]=useState(true),[companyRevision,setCompanyRevision]=useState(0),[company,setCompany]=useState<CompanyInfo>(),[branches,setBranches]=useState<BranchInfo[]>([]),[name,setName]=useState(''),[taxId,setTaxId]=useState(''),[draft,setDraft]=useState<BranchDraft>({name:'',code:'',city:''}),[original,setOriginal]=useState<BranchInfo>(),[page,setPage]=useState(1),[search,setSearch]=useState(''),[total,setTotal]=useState(0),[totalPages,setTotalPages]=useState(1),[revision,setRevision]=useState(0),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[blocked,setBlocked]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const lock=useRef(false),alive=useRef(true),controller=useRef<AbortController|undefined>(undefined);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;controller.current?.abort();};},[]);
 useEffect(()=>{const c=new AbortController();setCompanyLoading(true);setCompanyError('');loadCompany(base,token,co,c.signal).then(r=>{if(!c.signal.aborted){setCompany(r);setName(r.name);setTaxId(r.taxId);}}).catch(e=>{if(!c.signal.aborted){setCompany(undefined);setCompanyError(e instanceof Error?e.message:'No se pudo consultar la empresa.');if(e instanceof ApiError&&e.status===401)onExpired?.();}}).finally(()=>{if(!c.signal.aborted)setCompanyLoading(false);});return()=>c.abort();},[base,token,co,companyRevision,onExpired]);
 useEffect(()=>{const c=new AbortController();setLoading(true);setError('');setBranches([]);loadBranches(base,token,co,page,search,c.signal).then(r=>{if(!c.signal.aborted){setBranches(r.items);setTotal(r.total);setTotalPages(r.totalPages);}}).catch(e=>{if(!c.signal.aborted){setError(e instanceof Error?e.message:'No se pudo consultar sucursales.');if(e instanceof ApiError&&e.status===401)onExpired?.();}}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[base,token,co,page,search,revision,onExpired]);
 const locked=busy||blocked||loading||companyLoading;
 const companyReady=!locked&&!!company&&company.status==='ACTIVE'&&name.trim().length>=2&&name.trim().length<=160&&taxId.trim().length>=3&&taxId.trim().length<=32&&(company.name!==name.trim()||company.taxId!==taxId.trim().toUpperCase());
 const branchReady=!locked&&company?.status==='ACTIVE'&&validBranch(draft)&&(!original||original.name!==draft.name.trim()||original.code!==draft.code.trim().toUpperCase()||original.city!==draft.city.trim());
 async function save(kind:'company'|'branch'){
 if(lock.current||(kind==='company'?!companyReady:!branchReady))return;lock.current=true;controller.current=new AbortController();setBusy(true);setError('');setMessage('');
 try{if(kind==='company'){const r=await saveCompany(base,token,company!,name,taxId,controller.current.signal);if(alive.current){setCompany(r);setMessage('Empresa actualizada.');}}else{const r=await saveBranch(base,token,co,draft,original,controller.current.signal);if(alive.current){setOriginal(undefined);setDraft({name:'',code:'',city:''});setMessage('Sucursal confirmada: '+r.name);setPage(1);setRevision(v=>v+1);}}}catch(e){if(alive.current){setBlocked(!(e instanceof ApiError&&e.status===400));setError(e instanceof Error?e.message:'Actualiza antes de reintentar.');if(e instanceof ApiError&&e.status===401)onExpired?.();}}finally{lock.current=false;controller.current=undefined;if(alive.current)setBusy(false);}
 }
 return {company,branches,name,setName,taxId,setTaxId,draft,setField:(key:keyof BranchDraft,value:string)=>setDraft(v=>({...v,[key]:value})),original,edit:(r:BranchInfo)=>{if(locked||!r.isActive)return;setOriginal({...r});setDraft({name:r.name,code:r.code,city:r.city});setMessage('');},page,search,setSearch:(v:string)=>{setSearch(v);setPage(1);},total,totalPages,loading:loading||companyLoading,busy,locked,error:error||companyError,message,companyReady,branchReady,save,previous:()=>setPage(v=>Math.max(1,v-1)),next:()=>setPage(v=>Math.min(totalPages,v+1)),refresh:()=>{if(busy)return;setBlocked(false);setOriginal(undefined);setDraft({name:'',code:'',city:''});setPage(1);setCompanyRevision(v=>v+1);setRevision(v=>v+1);}};
}
