import {useEffect,useRef,useState} from 'react';import {ApiError} from './api';import {shipmentSales,saveShipment,type Shipment,type ShipmentSale} from './shipmentApi';
export function useShipmentForm(base:string,token:string,co:string,br:string,onSaved:()=>void,original?:Shipment,onExpired?:()=>void){
 const [destination,setDestination]=useState(''),[scheduledDate,setScheduledDate]=useState(new Date().toISOString().slice(0,10)),[status,setStatus]=useState<Shipment['status']>(original?.status==='IN_TRANSIT'?'DELIVERED':'IN_TRANSIT'),[sale,setSale]=useState<ShipmentSale|null>(null),[page,setPage]=useState<{items:ShipmentSale[];nextCursor:string|null}>({items:[],nextCursor:null}),[cursors,setCursors]=useState<Array<string|undefined>>([undefined]),[loading,setLoading]=useState(!original),[busy,setBusy]=useState(false),[blocked,setBlocked]=useState(false),[error,setError]=useState('');const lock=useRef(false),alive=useRef(true),write=useRef<AbortController|null>(null);const cursor=cursors[cursors.length-1];
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;write.current?.abort();};},[]);
 useEffect(()=>{if(original)return;const c=new AbortController();setLoading(true);setError('');shipmentSales(base,token,co,br,cursor,c.signal).then(p=>{if(!c.signal.aborted)setPage(p);}).catch(e=>{if(!c.signal.aborted){setPage({items:[],nextCursor:null});setError(e instanceof Error?e.message:'No se pudo consultar.');if(e instanceof ApiError&&e.status===401)onExpired?.();}}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[base,token,co,br,cursor,original,onExpired]);
 const ready=!busy&&!blocked&&(original?status!==original.status:!!sale&&destination.trim().length>=3&&!!scheduledDate);
 async function save(){if(!ready||lock.current)return;lock.current=true;setBusy(true);setError('');write.current=new AbortController();try{await saveShipment(base,token,co,br,{saleId:sale?.id,destination,scheduledDate,status},original,write.current.signal);if(alive.current)onSaved();}catch(e){if(alive.current){setBlocked(!(e instanceof ApiError&&e.status===400));setError(e instanceof Error?e.message:'Actualiza antes de reintentar.');if(e instanceof ApiError&&e.status===401)onExpired?.();}}finally{lock.current=false;write.current=null;if(alive.current)setBusy(false);}}
 return {destination,setDestination,scheduledDate,setScheduledDate,status,setStatus,sale,setSale,page,loading,busy,blocked,error,ready,save,pageNumber:cursors.length,previous:()=>setCursors(v=>v.length>1?v.slice(0,-1):v),next:()=>{if(page.nextCursor)setCursors(v=>[...v,page.nextCursor!]);}};
}
