import {useEffect,useRef,useState} from 'react';
import {ApiError} from './api';
import {assignableRoles,saveUser,validUserDraft,type AssignableRole} from './userCreationApi';
export function useUserCreation(base:string,token:string,co:string,br:string,permissions:string[],onCreated:()=>void,onExpired?:()=>void){
 const [name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[roles,setRoles]=useState<AssignableRole[]>([]),[roleId,setRoleId]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[blocked,setBlocked]=useState(false),[message,setMessage]=useState(''),[revision,setRevision]=useState(0);const lock=useRef(false),alive=useRef(true),write=useRef<AbortController|null>(null);const permissionKey=JSON.stringify(permissions);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;write.current?.abort();};},[]);
 useEffect(()=>{const c=new AbortController();setLoading(true);setRoles([]);setRoleId('');assignableRoles(base,token,co,JSON.parse(permissionKey),c.signal).then(rows=>{if(!c.signal.aborted)setRoles(rows);}).catch(e=>{if(!c.signal.aborted){if(e instanceof ApiError&&e.status===401)onExpired?.();setMessage(e instanceof Error?e.message:'No se pudieron consultar los roles.');}}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[base,token,co,permissionKey,revision,onExpired]);
 const role=roles.find(r=>r.id===roleId),ready=!loading&&!busy&&!blocked&&!!role&&validUserDraft(name,email,password);
 async function save(){if(!ready||!role||lock.current)return;lock.current=true;write.current=new AbortController();setBusy(true);setMessage('');try{await saveUser(base,token,co,br,{name,email,password},role,permissions,write.current.signal);if(alive.current){setName('');setEmail('');setPassword('');setMessage('Usuario creado correctamente.');onCreated();}}catch(e){if(alive.current){setPassword('');if(e instanceof ApiError&&e.status===401)onExpired?.();const known=e instanceof ApiError&&[400,401,403,409].includes(e.status);setBlocked(!known);setMessage(known?e.message:'No se pudo confirmar el alta. Consulta la lista antes de volver a crear la cuenta.');}}finally{lock.current=false;write.current=null;if(alive.current)setBusy(false);}}
 return {name,setName,email,setEmail,password,setPassword,roles,roleId,setRoleId,role,loading,busy,blocked,message,ready,save,refreshRoles:()=>setRevision(v=>v+1)};
}
