import mongoose from 'mongoose';import {z} from 'zod';import {AppError} from '../../errors/AppError.js';import {catalogFilter,catalogSlice} from '../../core/catalogPagination.js';import {getShipmentModel} from './models/Shipment.js';import {getSaleModel} from '../ventas/models/Sale.js';import {getCustomerModel} from '../clientes/models/Customer.js';import {getAuditEventModel} from '../auditoria/models/AuditEvent.js';
const id=z.string().regex(/^[a-f0-9]{24}$/i);const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>{const d=new Date(v+'T00:00:00Z');return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===v;});
export const shipmentCreateSchema=z.object({saleId:id,destination:z.string().trim().min(3).max(300),scheduledDate:date}).strict();
export const shipmentStateSchema=z.object({status:z.enum(['IN_TRANSIT','DELIVERED','CANCELLED']),expectedStatus:z.enum(['PENDING','IN_TRANSIT']),expectedUpdatedAt:z.string().datetime()}).strict().refine(v=>v.status==='CANCELLED'||v.expectedStatus==='PENDING'&&v.status==='IN_TRANSIT'||v.expectedStatus==='IN_TRANSIT'&&v.status==='DELIVERED');
const querySchema=z.object({search:z.string().trim().max(100).default(''),status:z.enum(['PENDING','IN_TRANSIT','DELIVERED','CANCELLED']).optional(),cursor:id.optional(),limit:z.coerce.number().int().min(1).max(50).default(20)}).strict();
const invalid=()=>new AppError({code:'VALIDATION_ERROR',message:'Invalid shipment',friendlyMessage:'Revisa venta, destino, fecha y estado del envío.',statusCode:400});
export function parseShipmentPage(raw:unknown){const p=querySchema.safeParse(raw);if(!p.success)throw invalid();return p.data;}
type Scope={companyId:string;branchId:string;userId:string;ipAddress?:string};
export async function pageShipments(scope:Scope,q:ReturnType<typeof parseShipmentPage>){const {status,...query}=q;const filter=catalogFilter({companyId:scope.companyId,branchId:scope.branchId},query,['destination']);if(status)filter.status=status;const rows=await getShipmentModel().find(filter).sort({_id:-1}).limit(q.limit+1).lean().exec();const sales=await getSaleModel().find({companyId:scope.companyId,branchId:scope.branchId,_id:{$in:rows.map(r=>r.saleId).filter(v=>/^[a-f0-9]{24}$/i.test(v))}}).select('customerId').lean().exec();const customers=await getCustomerModel().find({companyId:scope.companyId,branchId:scope.branchId,_id:{$in:sales.map(r=>r.customerId).filter(v=>/^[a-f0-9]{24}$/i.test(v))}}).select('name').lean().exec();const names=new Map(customers.map(c=>[String(c._id),c.name]));const saleNames=new Map(sales.map(s=>[String(s._id),names.get(s.customerId)]));return catalogSlice(rows.map(r=>({...r,customerName:saleNames.get(r.saleId)})),q.limit);}
export async function administerShipment(scope:Scope,payload:unknown,shipmentId?:string){const p=shipmentId?shipmentStateSchema.safeParse(payload):shipmentCreateSchema.safeParse(payload);if(!p.success||!scope.userId||shipmentId&&!id.safeParse(shipmentId).success)throw invalid();await Promise.all([getShipmentModel().init(),getAuditEventModel().init()]);const session=await mongoose.startSession();let result;
try{await session.withTransaction(async()=>{let row;if(shipmentId){const input=p.data as z.infer<typeof shipmentStateSchema>;row=await getShipmentModel().findOneAndUpdate({_id:shipmentId,companyId:scope.companyId,branchId:scope.branchId,status:input.expectedStatus,updatedAt:new Date(input.expectedUpdatedAt)},{$set:{status:input.status}},{new:true,session}).lean().exec();if(!row)throw new AppError({code:'CONFLICT',message:'Shipment changed',friendlyMessage:'El envío cambió o ya está cerrado. Actualiza antes de reintentar.',statusCode:409});if(input.status!=='CANCELLED'&&!await getSaleModel().exists({_id:row.saleId,companyId:scope.companyId,branchId:scope.branchId,status:{$ne:'CANCELADA'}}).session(session))throw invalid();}else{const input=p.data as z.infer<typeof shipmentCreateSchema>;if(!await getSaleModel().exists({_id:input.saleId,companyId:scope.companyId,branchId:scope.branchId,status:{$ne:'CANCELADA'}}).session(session))throw invalid();const [created]=await getShipmentModel().create([{...input,companyId:scope.companyId,branchId:scope.branchId,status:'PENDING'}],{session});row=created.toObject();}await getAuditEventModel().create([{userId:scope.userId,companyId:scope.companyId,branchId:scope.branchId,action:shipmentId?'UPDATE':'CREATE',module:'logistica',entityId:String(row._id),details:{status:row.status,saleId:row.saleId},ipAddress:scope.ipAddress}],{session});const {_id,...rest}=row;result={id:String(_id),...rest};});return result!;}finally{await session.endSession();}}
