import mongoose from 'mongoose';import {z} from 'zod';import {AppError} from '../../errors/AppError.js';import {catalogFilter,catalogSlice} from '../../core/catalogPagination.js';import {getManagedAssetModel} from './models/ManagedAsset.js';import {getAuditEventModel} from '../auditoria/models/AuditEvent.js';
const status=z.enum(['operational','maintenance','offline','retired']);const id=z.string().regex(/^[a-f0-9]{24}$/i);
export const assetCreateSchema=z.object({name:z.string().trim().min(2).max(120),code:z.string().trim().min(2).max(32).regex(/^[A-Za-z0-9_-]+$/).transform(v=>v.toUpperCase()),location:z.string().trim().min(2).max(200)}).strict();
export const assetUpdateSchema=z.object({name:z.string().trim().min(2).max(120),location:z.string().trim().min(2).max(200),status,expectedStatus:z.enum(['operational','maintenance','offline']),expectedUpdatedAt:z.string().datetime()}).strict();
const query=z.object({search:z.string().trim().max(100).default(''),status:status.optional(),cursor:id.optional(),limit:z.coerce.number().int().min(1).max(50).default(20)}).strict();
const invalid=()=>new AppError({code:'VALIDATION_ERROR',message:'Invalid asset',friendlyMessage:'Revisa nombre, código, ubicación y estado del activo.',statusCode:400});
type Scope={companyId:string;branchId:string;userId:string;ipAddress?:string};
export function parseAssetPage(raw:unknown){const p=query.safeParse(raw);if(!p.success)throw invalid();return p.data;}
export async function pageAssets(scope:Scope,q:ReturnType<typeof parseAssetPage>){const {status,...rest}=q;const filter=catalogFilter({companyId:scope.companyId,branchId:scope.branchId},rest,['name','code','location']);if(status)filter.status=status;return catalogSlice(await getManagedAssetModel().find(filter).sort({_id:-1}).limit(q.limit+1).lean().exec(),q.limit);}
export async function assetSummary(scope:Scope){const rows=await getManagedAssetModel().aggregate([{$match:{companyId:scope.companyId,branchId:scope.branchId}},{$group:{_id:'$status',count:{$sum:1}}}]);const counts={operational:0,maintenance:0,offline:0,retired:0};for(const r of rows)if(r._id in counts)counts[r._id as keyof typeof counts]=r.count;return {counts,total:Object.values(counts).reduce((a,b)=>a+b,0)};}
export async function administerAsset(scope:Scope,payload:unknown,assetId?:string){const p=assetId?assetUpdateSchema.safeParse(payload):assetCreateSchema.safeParse(payload);if(!p.success||!scope.userId||assetId&&!id.safeParse(assetId).success)throw invalid();await Promise.all([getManagedAssetModel().init(),getAuditEventModel().init()]);const session=await mongoose.startSession();let result;try{await session.withTransaction(async()=>{let row;if(assetId){const input=p.data as z.infer<typeof assetUpdateSchema>;row=await getManagedAssetModel().findOneAndUpdate({_id:assetId,companyId:scope.companyId,branchId:scope.branchId,status:input.expectedStatus,updatedAt:new Date(input.expectedUpdatedAt)},{$set:{name:input.name,location:input.location,status:input.status}},{new:true,session}).lean().exec();if(!row)throw new AppError({code:'CONFLICT',message:'Asset changed',friendlyMessage:'El activo cambió o está retirado. Actualiza antes de reintentar.',statusCode:409});}else{const [created]=await getManagedAssetModel().create([{...p.data,companyId:scope.companyId,branchId:scope.branchId,status:'operational'}],{session});row=created.toObject();}await getAuditEventModel().create([{userId:scope.userId,companyId:scope.companyId,branchId:scope.branchId,action:assetId?'UPDATE':'CREATE',module:'activos',entityId:String(row._id),details:{name:row.name,code:row.code,location:row.location,status:row.status},ipAddress:scope.ipAddress}],{session});const {_id,...rest}=row;result={id:String(_id),...rest};});return result!;}catch(e){if((e as {code?:number}).code===11000)throw new AppError({code:'CONFLICT',message:'Duplicate asset code',friendlyMessage:'Ese código ya existe en la sucursal.',statusCode:409});throw e;}finally{await session.endSession();}}
