import mongoose from 'mongoose';import {z} from 'zod';import {AppError} from '../../errors/AppError.js';import {catalogFilter,catalogSlice} from '../../core/catalogPagination.js';import {getRiskRecordModel} from './models/RiskRecord.js';import {getAuditEventModel} from '../auditoria/models/AuditEvent.js';
const id=z.string().regex(/^[a-f0-9]{24}$/i);const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>{const d=new Date(v+'T00:00:00Z');return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===v;});
export const riskCreateSchema=z.object({name:z.string().trim().min(2).max(120),mitigationPlan:z.string().trim().min(3).max(1000),reviewDate:date,level:z.enum(['low','medium','high'])}).strict();
export const riskStateSchema=z.object({status:z.enum(['mitigating','closed','dismissed']),expectedStatus:z.enum(['identified','mitigating']),expectedUpdatedAt:z.string().datetime(),completionNote:z.string().trim().min(3).max(1000).optional()}).strict().refine(v=>(v.status==='dismissed'||v.expectedStatus==='identified'&&v.status==='mitigating'||v.expectedStatus==='mitigating'&&v.status==='closed')&&(v.status==='closed'?!!v.completionNote:v.completionNote===undefined));
const querySchema=z.object({search:z.string().trim().max(100).default(''),status:z.enum(['identified','mitigating','closed','dismissed']).optional(),cursor:id.optional(),limit:z.coerce.number().int().min(1).max(50).default(20)}).strict();
const invalid=()=>new AppError({code:'VALIDATION_ERROR',message:'Invalid risk order',friendlyMessage:'Revisa nombre, plan de mitigación, fecha de revisión, nivel y conclusión.',statusCode:400});
export function parseRiskPage(raw:unknown){const p=querySchema.safeParse(raw);if(!p.success)throw invalid();return p.data;}
type Scope={companyId:string;branchId:string;userId:string;ipAddress?:string};
export async function pageRisks(scope:Scope,q:ReturnType<typeof parseRiskPage>){const {status,...query}=q;const filter=catalogFilter({companyId:scope.companyId,branchId:scope.branchId},query,['name','mitigationPlan']);if(status)filter.status=status;return catalogSlice(await getRiskRecordModel().find(filter).sort({_id:-1}).limit(q.limit+1).lean().exec(),q.limit);}
export async function riskSummary(scope:Scope){const rows=await getRiskRecordModel().aggregate([{$match:{companyId:scope.companyId,branchId:scope.branchId}},{$group:{_id:'$status',count:{$sum:1}}}]);const counts={identified:0,mitigating:0,closed:0,dismissed:0};for(const row of rows)if(row._id in counts)counts[row._id as keyof typeof counts]=row.count;return {counts,total:Object.values(counts).reduce((a,b)=>a+b,0)};}
export async function administerRisk(scope:Scope,payload:unknown,orderId?:string){const p=orderId?riskStateSchema.safeParse(payload):riskCreateSchema.safeParse(payload);if(!p.success||!scope.userId||orderId&&!id.safeParse(orderId).success)throw invalid();await Promise.all([getRiskRecordModel().init(),getAuditEventModel().init()]);const session=await mongoose.startSession();let result;
try{await session.withTransaction(async()=>{let row;if(orderId){const input=p.data as z.infer<typeof riskStateSchema>;row=await getRiskRecordModel().findOneAndUpdate({_id:orderId,companyId:scope.companyId,branchId:scope.branchId,status:input.expectedStatus,updatedAt:new Date(input.expectedUpdatedAt)},{$set:{status:input.status,...(input.completionNote?{completionNote:input.completionNote}:{})}},{new:true,session}).lean().exec();if(!row)throw new AppError({code:'CONFLICT',message:'Support changed',friendlyMessage:'El riesgo cambió o ya está cerrado. Actualiza antes de reintentar.',statusCode:409});}else{const [created]=await getRiskRecordModel().create([{...p.data,companyId:scope.companyId,branchId:scope.branchId,status:'identified'}],{session});row=created.toObject();}await getAuditEventModel().create([{userId:scope.userId,companyId:scope.companyId,branchId:scope.branchId,action:orderId?'UPDATE':'CREATE',module:'riesgo',entityId:String(row._id),details:{status:row.status,name:row.name,completionNote:row.completionNote},ipAddress:scope.ipAddress}],{session});const {_id,...rest}=row;result={id:String(_id),...rest};});return result!;}finally{await session.endSession();}}
