import mongoose from 'mongoose';import {z} from 'zod';import {AppError} from '../../errors/AppError.js';import {catalogFilter,catalogSlice} from '../../core/catalogPagination.js';import {getSupportTicketModel} from './models/SupportTicket.js';import {getAuditEventModel} from '../auditoria/models/AuditEvent.js';
const id=z.string().regex(/^[a-f0-9]{24}$/i);const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>{const d=new Date(v+'T00:00:00Z');return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===v;});
export const ticketCreateSchema=z.object({subject:z.string().trim().min(2).max(120),description:z.string().trim().min(3).max(1000),targetDate:date,priority:z.enum(['low','medium','high'])}).strict();
export const ticketStateSchema=z.object({status:z.enum(['in_progress','resolved','cancelled']),expectedStatus:z.enum(['open','in_progress']),expectedUpdatedAt:z.string().datetime(),completionNote:z.string().trim().min(3).max(1000).optional()}).strict().refine(v=>(v.status==='cancelled'||v.expectedStatus==='open'&&v.status==='in_progress'||v.expectedStatus==='in_progress'&&v.status==='resolved')&&(v.status==='resolved'?!!v.completionNote:v.completionNote===undefined));
const querySchema=z.object({search:z.string().trim().max(100).default(''),status:z.enum(['open','in_progress','resolved','cancelled']).optional(),cursor:id.optional(),limit:z.coerce.number().int().min(1).max(50).default(20)}).strict();
const invalid=()=>new AppError({code:'VALIDATION_ERROR',message:'Invalid ticket order',friendlyMessage:'Revisa asunto, descripción, fecha objetivo, prioridad y resolución.',statusCode:400});
export function parseTicketPage(raw:unknown){const p=querySchema.safeParse(raw);if(!p.success)throw invalid();return p.data;}
type Scope={companyId:string;branchId:string;userId:string;ipAddress?:string};
export async function pageTickets(scope:Scope,q:ReturnType<typeof parseTicketPage>){const {status,...query}=q;const filter=catalogFilter({companyId:scope.companyId,branchId:scope.branchId},query,['subject','description']);if(status)filter.status=status;return catalogSlice(await getSupportTicketModel().find(filter).sort({_id:-1}).limit(q.limit+1).lean().exec(),q.limit);}
export async function ticketSummary(scope:Scope){const rows=await getSupportTicketModel().aggregate([{$match:{companyId:scope.companyId,branchId:scope.branchId}},{$group:{_id:'$status',count:{$sum:1}}}]);const counts={open:0,in_progress:0,resolved:0,cancelled:0};for(const row of rows)if(row._id in counts)counts[row._id as keyof typeof counts]=row.count;return {counts,total:Object.values(counts).reduce((a,b)=>a+b,0)};}
export async function administerTicket(scope:Scope,payload:unknown,orderId?:string){const p=orderId?ticketStateSchema.safeParse(payload):ticketCreateSchema.safeParse(payload);if(!p.success||!scope.userId||orderId&&!id.safeParse(orderId).success)throw invalid();await Promise.all([getSupportTicketModel().init(),getAuditEventModel().init()]);const session=await mongoose.startSession();let result;
try{await session.withTransaction(async()=>{let row;if(orderId){const input=p.data as z.infer<typeof ticketStateSchema>;row=await getSupportTicketModel().findOneAndUpdate({_id:orderId,companyId:scope.companyId,branchId:scope.branchId,status:input.expectedStatus,updatedAt:new Date(input.expectedUpdatedAt)},{$set:{status:input.status,...(input.completionNote?{completionNote:input.completionNote}:{})}},{new:true,session}).lean().exec();if(!row)throw new AppError({code:'CONFLICT',message:'Support changed',friendlyMessage:'El ticket cambió o ya está cerrado. Actualiza antes de reintentar.',statusCode:409});}else{const [created]=await getSupportTicketModel().create([{...p.data,companyId:scope.companyId,branchId:scope.branchId,status:'open'}],{session});row=created.toObject();}await getAuditEventModel().create([{userId:scope.userId,companyId:scope.companyId,branchId:scope.branchId,action:orderId?'UPDATE':'CREATE',module:'soporte',entityId:String(row._id),details:{status:row.status,subject:row.subject,completionNote:row.completionNote},ipAddress:scope.ipAddress}],{session});const {_id,...rest}=row;result={id:String(_id),...rest};});return result!;}finally{await session.endSession();}}
