import {test} from 'node:test';import assert from 'node:assert/strict';import {productionPage,productionAction,productionQuantity,createProduction} from '../src/productionApi';
const row={id:'000000000000000000000001',companyId:'co',branchId:'br',productId:'000000000000000000000002',plannedQuantity:6,completedQuantity:0,status:'running' as const};
test('production pages enforce scope, state and progress quantities',async t=>{const old=globalThis.fetch;t.after(()=>{globalThis.fetch=old;});globalThis.fetch=async()=>new Response(JSON.stringify({data:{items:[row],nextCursor:null}}));assert.equal((await productionPage('api','token','co','br','running')).items.length,1);for(const items of [[{...row,branchId:'foreign'}],[{...row,completedQuantity:7}],[row,row]]){globalThis.fetch=async()=>new Response(JSON.stringify({data:{items,nextCursor:null}}));await assert.rejects(productionPage('api','token','co','br','running'));}});
test('production completion confirms order and immutable stock receipt link',async t=>{const old=globalThis.fetch;t.after(()=>{globalThis.fetch=old;});const warehouseId='000000000000000000000003',complete={...row,status:'completed',completedQuantity:6,completionWarehouseId:warehouseId,completionMovementId:'000000000000000000000004'};globalThis.fetch=async(url,options)=>{assert.equal(String(url),'api/production/orders/'+row.id+'/complete');assert.deepEqual(JSON.parse(String(options?.body)),{warehouseId,expectedQuantity:6});return new Response(JSON.stringify({data:complete}));};assert.equal((await productionAction('api','token',row,'completed',warehouseId)).completedQuantity,6);globalThis.fetch=async()=>new Response(JSON.stringify({data:{...complete,completionMovementId:null}}));await assert.rejects(productionAction('api','token',row,'completed',warehouseId));globalThis.fetch=async()=>new Response('{}',{status:409});await assert.rejects(productionAction('api','token',row,'completed',warehouseId),(e:any)=>e.status===409);});
test('production quantities follow six decimal precision and safe upper limits',()=>{assert.equal(productionQuantity('0.000001'),0.000001);for(const value of ['0','1.0000001','1,5','Infinity','1000000001'])assert.ok(Number.isNaN(productionQuantity(value)));});

test('production names reject malformed server fields',async t=>{const old=globalThis.fetch;t.after(()=>{globalThis.fetch=old;});for(const key of ['productName','productSku','completionWarehouseName']){globalThis.fetch=async()=>new Response(JSON.stringify({data:{items:[{id:'000000000000000000000003',companyId:'co',branchId:'br',productId:'000000000000000000000001',plannedQuantity:1,completedQuantity:0,status:'planned',[key]:42}],nextCursor:null}}));await assert.rejects(productionPage('api','token','co','br',''));}});

test('production creation sends scoped material quantities and rejects duplicate or self consumption',async t=>{const old=globalThis.fetch;t.after(()=>{globalThis.fetch=old;});const material={productId:'000000000000000000000005',warehouseId:'000000000000000000000003',quantity:0.000001,productName:'Material',warehouseName:'Origin'};globalThis.fetch=async(_url,options)=>{const input=JSON.parse(String(options?.body));assert.deepEqual(input.materials,[{productId:material.productId,warehouseId:material.warehouseId,quantity:material.quantity}]);return new Response(JSON.stringify({data:{...row,status:'planned',materials:input.materials}}));};assert.equal((await createProduction('api','token','co','br',row.productId,'6',undefined,[material])).materials?.length,1);await assert.rejects(createProduction('api','token','co','br',row.productId,'6',undefined,[material,material]));await assert.rejects(createProduction('api','token','co','br',row.productId,'6',undefined,[{...material,productId:row.productId}]));});
test('production completion requires all consumed material movement links and preserves the plan',async t=>{const old=globalThis.fetch;t.after(()=>{globalThis.fetch=old;});const warehouseId='000000000000000000000003',material={productId:'000000000000000000000005',warehouseId,quantity:3};const original={...row,materials:[material]},complete={...original,status:'completed',completedQuantity:6,completionWarehouseId:warehouseId,completionMovementId:'000000000000000000000004',materials:[{...material,movementId:'000000000000000000000006'}]};globalThis.fetch=async()=>new Response(JSON.stringify({data:complete}));await productionAction('api','token',original,'completed',warehouseId);for(const materials of [[],[material],[{...complete.materials[0],quantity:4}]]){globalThis.fetch=async()=>new Response(JSON.stringify({data:{...complete,materials}}));await assert.rejects(productionAction('api','token',original,'completed',warehouseId));}});

test('partial production confirms the increment and expected version and rejects inconsistent progress',async t=>{const old=globalThis.fetch;t.after(()=>{globalThis.fetch=old;});const warehouseId='000000000000000000000003',original={...row,updatedAt:'2026-10-06T10:00:00.000Z',deliveries:[]};const delivered={quantity:2,warehouseId,movementId:'000000000000000000000004',materials:[]};const result={...original,completedQuantity:2,completionWarehouseId:warehouseId,completionMovementId:delivered.movementId,updatedAt:'2026-10-06T10:00:01.000Z',deliveries:[delivered]};globalThis.fetch=async(_url,options)=>{assert.deepEqual(JSON.parse(String(options?.body)),{warehouseId,expectedQuantity:6,deliveredQuantity:2,expectedCompletedQuantity:0,expectedUpdatedAt:original.updatedAt});return new Response(JSON.stringify({data:result}));};assert.equal((await productionAction('api','token',original,'completed',warehouseId,undefined,2)).status,'running');globalThis.fetch=async()=>new Response(JSON.stringify({data:{...result,completedQuantity:3}}));await assert.rejects(productionAction('api','token',original,'completed',warehouseId,undefined,2));await assert.rejects(productionAction('api','token',original,'completed',warehouseId,undefined,7));});

test('production delivery confirms manual cost and preserves the currency',async t=>{const old=globalThis.fetch;t.after(()=>{globalThis.fetch=old;});const warehouseId='000000000000000000000003',original={...row,updatedAt:'2026-10-06T10:00:00.000Z',deliveries:[]},delivery={quantity:2,warehouseId,movementId:'000000000000000000000004',materials:[],cost:3.5};const result={...original,completedQuantity:2,completionWarehouseId:warehouseId,completionMovementId:delivery.movementId,updatedAt:'2026-10-06T10:00:01.000Z',deliveries:[delivery],productionCost:3.5,costCurrency:'MXN'};globalThis.fetch=async(_url,options)=>{const body=JSON.parse(String(options?.body));assert.equal(body.cost,3.5);assert.equal(body.currency,'MXN');return new Response(JSON.stringify({data:result}));};assert.equal((await productionAction('api','token',original,'completed',warehouseId,undefined,2,{amount:3.5,currency:'MXN'})).productionCost,3.5);globalThis.fetch=async()=>new Response(JSON.stringify({data:{...result,productionCost:4}}));await assert.rejects(productionAction('api','token',original,'completed',warehouseId,undefined,2,{amount:3.5,currency:'MXN'}));await assert.rejects(productionAction('api','token',original,'completed',warehouseId,undefined,2,{amount:0.001,currency:'MXN'}));});
