import {useEffect,useState} from 'react';
import {financePage,type FinanceAccount} from './financeApi';
async function accountPage(base:string,token:string,signal:AbortSignal,search:string,cursor:string){const page=await financePage(base,token,'bank-accounts',signal,search,cursor,'','ACTIVE');return {items:page.items as FinanceAccount[],nextCursor:page.nextCursor};}
export function AccountSelector({apiUrl,token,label,selected,disabled,onSelect}:{apiUrl:string;token:string;label:string;selected:FinanceAccount|null;disabled:boolean;onSelect:(row:FinanceAccount)=>void}) {
 const [search,setSearch]=useState(''),[applied,setApplied]=useState(''),[cursors,setCursors]=useState(['']),[next,setNext]=useState<string|null>(null),[rows,setRows]=useState<FinanceAccount[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[revision,setRevision]=useState(0);const cursor=cursors[cursors.length-1],kind='settlement-accounts';
 useEffect(()=>{const c=new AbortController();setLoading(true);setError('');setRows([]);setNext(null);accountPage(apiUrl,token,c.signal,applied,cursor).then(page=>{if(!c.signal.aborted){setRows(page.items);setNext(page.nextCursor);}}).catch(e=>{if(!c.signal.aborted)setError(e instanceof Error?e.message:'No se pudo consultar.');}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[apiUrl,token,label,applied,cursor,revision]);
 const locked=disabled||loading;
 return <div className="panel"><h4>{label}</h4>{selected&&<p>Seleccionado: {selected.name}{selected.bankName?' · '+selected.bankName:''}</p>}<div className="field"><label htmlFor={kind+'-selector-search'}>Buscar {label.toLowerCase()}</label><input id={kind+'-selector-search'} value={search} maxLength={100} disabled={disabled} onChange={e=>setSearch(e.target.value)}/></div><div style={{display:'flex',gap:8}}><button type="button" disabled={locked} onClick={()=>{setApplied(search.trim());setCursors(['']);setRevision(v=>v+1);}}>Buscar</button><button type="button" disabled={locked} onClick={()=>{setSearch('');setApplied('');setCursors(['']);setRevision(v=>v+1);}}>Ver todos</button></div>{loading?<p>Consultando…</p>:error?<p role="alert" className="error-box">{error}</p>:<><p>Página {cursors.length} · {rows.length} registros</p>{!rows.length&&<p>No hay registros activos para esta búsqueda.</p>}<div className="data-list">{rows.map(row=><div className="data-row" key={row.id}><span><strong>{row.name}</strong><small>{row.bankName}</small></span><button type="button" disabled={disabled} aria-pressed={selected?.id===row.id} onClick={()=>onSelect(row)}>{selected?.id===row.id?'Seleccionado':'Seleccionar'}</button></div>)}</div></>}<div style={{display:'flex',gap:8,marginTop:12}}><button type="button" disabled={locked||cursors.length===1} onClick={()=>setCursors(v=>v.slice(0,-1))}>Anterior</button><button type="button" disabled={locked||!next} onClick={()=>{if(next)setCursors(v=>[...v,next]);}}>Siguiente</button><button type="button" disabled={locked} onClick={()=>{setCursors(['']);setRevision(v=>v+1);}}>{error?'Reintentar':'Actualizar'}</button></div></div>;
}
