import {useEffect,useState} from 'react';
import {warehousePageRequest,type WarehouseEntry} from './inventoryApi';
import {categoryPageRequest} from './categoryApi';
export function AdminSelector({apiUrl,token,label,kind,selected,disabled,onSelect}:{apiUrl:string;token:string;label:string;kind:'categories'|'warehouses';selected:WarehouseEntry|null;disabled:boolean;onSelect:(row:WarehouseEntry)=>void}) {
 const [search,setSearch]=useState(''),[applied,setApplied]=useState(''),[cursors,setCursors]=useState(['']),[next,setNext]=useState<string|null>(null),[rows,setRows]=useState<WarehouseEntry[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[revision,setRevision]=useState(0);const cursor=cursors[cursors.length-1];
 useEffect(()=>{const c=new AbortController();setLoading(true);setError('');setRows([]);setNext(null);(kind==='categories'?categoryPageRequest:warehousePageRequest)(apiUrl,token,c.signal,applied,cursor).then(page=>{if(!c.signal.aborted){setRows(page.items);setNext(page.nextCursor);}}).catch(e=>{if(!c.signal.aborted)setError(e instanceof Error?e.message:'No se pudo consultar.');}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[apiUrl,token,label,kind,kind,applied,cursor,revision]);
 const locked=disabled||loading;
 return <div className="panel"><h4>{label}</h4>{selected&&<p>Seleccionado: {selected.name}{selected.code?' · '+selected.code:''}</p>}<div className="field"><label htmlFor={kind+'-selector-search'}>Buscar {label.toLowerCase()}</label><input id={kind+'-selector-search'} value={search} maxLength={100} disabled={disabled} onChange={e=>setSearch(e.target.value)}/></div><div style={{display:'flex',gap:8}}><button type="button" disabled={locked} onClick={()=>{setApplied(search.trim());setCursors(['']);setRevision(v=>v+1);}}>Buscar</button><button type="button" disabled={locked} onClick={()=>{setSearch('');setApplied('');setCursors(['']);setRevision(v=>v+1);}}>Ver todos</button></div>{loading?<p>Consultando…</p>:error?<p role="alert" className="error-box">{error}</p>:<><p>Página {cursors.length} · {rows.length} registros</p>{!rows.length&&<p>No hay registros para esta búsqueda.</p>}<div className="data-list">{rows.map(row=><div className="data-row" key={row.id}><span><strong>{row.name}</strong><small>{row.code} · {row.status}</small></span><button type="button" disabled={disabled} aria-pressed={selected?.id===row.id} onClick={()=>onSelect(row)}>{selected?.id===row.id?'Seleccionado':'Seleccionar'}</button></div>)}</div></>}<div style={{display:'flex',gap:8,marginTop:12}}><button type="button" disabled={locked||cursors.length===1} onClick={()=>setCursors(v=>v.slice(0,-1))}>Anterior</button><button type="button" disabled={locked||!next} onClick={()=>{if(next)setCursors(v=>[...v,next]);}}>Siguiente</button><button type="button" disabled={locked} onClick={()=>{setCursors(['']);setRevision(v=>v+1);}}>{error?'Reintentar':'Actualizar'}</button></div></div>;
}
