import {useEffect,useRef,useState,type FormEvent} from 'react';
import {CategorySelector} from './CategorySelector';
import {categoryLookup,type CategoryRow} from './categoryApi';
import {updatePartner,updateProductRequest,validatePartner,validateProduct} from './catalogEditApi';
import type {CatalogEntry,CatalogKind} from './catalogApi';
export function CatalogEdit({apiUrl,token,kind,entry,onSaved,onCancel}:{apiUrl:string;token:string;kind:CatalogKind;entry:CatalogEntry;onSaved:()=>void;onCancel:()=>void}) {
 const [draft,setDraft]=useState({name:entry.name,taxId:entry.taxId??'',email:entry.email??'',sku:entry.sku??'',categoryId:entry.categoryId??'',price:String(entry.price??0)}),[category,setCategory]=useState<CategoryRow|null>(null),[saving,setSaving]=useState(false),[error,setError]=useState('');const write=useRef<AbortController|null>(null);
 useEffect(()=>()=>write.current?.abort(),[]);
 useEffect(()=>{if(kind!=='products'||!entry.categoryId)return;const c=new AbortController();categoryLookup(apiUrl,token,c.signal,[entry.categoryId]).then(rows=>{if(!c.signal.aborted)setCategory(rows[0]??null);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[apiUrl,token,kind,entry.categoryId]);
 async function submit(e:FormEvent){e.preventDefault();if(write.current)return;setError('');try{if(kind==='products'){validateProduct(draft);if(!category||category.status!=='ACTIVE'||category.id!==draft.categoryId)throw new Error('Selecciona una categoría activa.');}else validatePartner(draft);}catch(e){setError(e instanceof Error?e.message:'Revisa los datos.');return;}if(!window.confirm('Guardar cambios de '+entry.name+'?'))return;const c=new AbortController();write.current=c;setSaving(true);try{if(kind==='products')await updateProductRequest(apiUrl,token,entry.id,draft,c.signal,entry);else await updatePartner(apiUrl,kind,token,entry.id,draft,c.signal,entry);if(!c.signal.aborted)onSaved();}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:'Actualiza antes de repetir.');}finally{write.current=null;if(!c.signal.aborted)setSaving(false);}}
 return <form onSubmit={e=>void submit(e)} className="panel"><fieldset disabled={saving}><legend>Editar {entry.name}</legend>{(kind==='products'?['name','price']:['name','taxId','email']).map(field=><div className="field" key={field}><label htmlFor={'edit-'+field}>{field==='name'?'Nombre':field==='price'?'Precio':field==='taxId'?'Identificador fiscal':'Correo'}</label><input id={'edit-'+field} required type={field==='email'?'email':'text'} value={draft[field as keyof typeof draft]} onChange={e=>setDraft(v=>({...v,[field]:e.target.value}))}/></div>)}{kind==='products'&&<><p>SKU: {entry.sku}</p><CategorySelector apiUrl={apiUrl} token={token} label="Categoría activa" selected={category} disabled={saving} onSelect={row=>{setCategory(row);setDraft(v=>({...v,categoryId:row.id}));}}/></>}<button type="submit">{saving?'Guardando…':'Guardar cambios'}</button><button type="button" onClick={onCancel}>Cancelar</button></fieldset>{error&&<p role="alert">{error}</p>}</form>;
}
