import {useState} from 'react';import {useComplianceForm} from './useComplianceForm';import type {ComplianceControl} from './complianceApi';
import {DocumentExportButtons} from './DocumentExportButtons';import {complianceDocument} from './operationsDocument';
import {useCompliance} from './useCompliance';
type Props={base:string;token:string;companyId:string;branchId:string;canManage:boolean};
const labels:Record<string,string>={pending:'Pendiente',reviewing:'En revisión',completed:'Revisado',cancelled:'Cancelado',low:'Baja',medium:'Media',high:'Alta'};
const results:Record<string,string>={pass:'Conforme',watch:'Con observaciones',fail:'No conforme'};
export function CompliancePanel(p:Props){const s=useCompliance(p.base,p.token,p.companyId,p.branchId),[form,setForm]=useState<ComplianceControl|'new'|null>(null);const close=()=>{setForm(null);s.refresh();};return <section className="panel"><h2>Cumplimiento de tu sucursal</h2><p>Obligaciones internas registradas. Los resultados documentan una revisión interna.</p>{p.canManage&&<button disabled={!!form} onClick={()=>setForm('new')}>Nueva obligación</button>}{form&&<Form key={form==='new'?'new':form.id} {...p} original={form==='new'?undefined:form} onClose={close}/>}<label>Buscar obligación o requisito<input maxLength={100} value={s.search} onChange={e=>s.setSearch(e.target.value)}/></label><label>Estado<select value={s.status} onChange={e=>s.setStatus(e.target.value)}><option value="">Todos</option>{['pending','reviewing','completed','cancelled'].map(v=><option key={v} value={v}>{labels[v]}</option>)}</select></label><button disabled={s.loading} onClick={s.apply}>Buscar</button>{s.loading&&<p>Consultando…</p>}{s.error&&<p role="alert">{s.error}</p>}{!s.loading&&!s.error&&!s.page.items.length&&<p>No hay registros para esta búsqueda.</p>}{s.page.items.map(r=><article key={r.id}><h3>{r.name}</h3><p>{r.requirement}</p><p>{r.dueDate} · {labels[r.priority]} · {labels[r.status]}</p>{r.result&&<p>{results[r.result]}</p>}{r.evidenceNote&&<p>Resultado: {r.evidenceNote}</p>}<DocumentExportButtons document={complianceDocument(r)}/>{p.canManage&&['pending','reviewing'].includes(r.status)&&<button disabled={!!form} onClick={()=>setForm({...r})}>Cambiar estado</button>}</article>)}<p>Página {s.pageNumber}</p><button disabled={s.loading||s.pageNumber===1} onClick={s.previous}>Anterior</button><button disabled={s.loading||!!s.error||!s.page.nextCursor} onClick={s.next}>Siguiente</button><button disabled={s.loading} onClick={s.refresh}>Actualizar</button></section>;}


function Form(p:Props&{original?:ComplianceControl;onClose:()=>void}){const s=useComplianceForm(p.base,p.token,p.companyId,p.branchId,p.onClose,p.original),locked=s.busy||s.blocked;return <fieldset><legend>{p.original?'Estado de obligación':'Nueva obligación'}</legend>{p.original?<><p>{p.original.name} · {p.original.requirement}</p><label>Estado<select disabled={locked} value={s.status} onChange={e=>s.setStatus(e.target.value as ComplianceControl['status'])}><option value={p.original.status==='pending'?'reviewing':'completed'}>{p.original.status==='pending'?'En revisión':'Revisado'}</option><option value="cancelled">Cancelado</option></select></label>{s.status==='completed'&&<><label>Resultado<select disabled={locked} value={s.result} onChange={e=>s.setResult(e.target.value as ''|'pass'|'watch'|'fail')}><option value="">Selecciona un resultado</option>{Object.entries(results).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label><label>Evidencia y observaciones<textarea disabled={locked} maxLength={1000} value={s.evidenceNote} onChange={e=>s.setEvidenceNote(e.target.value)}/></label></>}<p>Revisado y cancelado son estados finales.</p></>:<><label>Obligación<input disabled={locked} maxLength={120} value={s.name} onChange={e=>s.setName(e.target.value)}/></label><label>Requisito<textarea disabled={locked} maxLength={1000} value={s.requirement} onChange={e=>s.setRequirement(e.target.value)}/></label><label>Fecha límite<input disabled={locked} type="date" value={s.dueDate} onChange={e=>s.setDueDate(e.target.value)}/></label><label>Prioridad<select disabled={locked} value={s.priority} onChange={e=>s.setPriority(e.target.value as ComplianceControl['priority'])}>{['low','medium','high'].map(v=><option key={v} value={v}>{labels[v]}</option>)}</select></label></>}{s.error&&<p role="alert">{s.error}</p>}<button disabled={!s.ready} onClick={()=>{if(window.confirm(p.original?'Cambiar obligación de '+p.original.name+' a '+labels[s.status]+'?':'Crear obligación de '+s.name.trim()+' para '+s.dueDate+'?'))void s.save();}}>Guardar obligación</button><button disabled={s.busy} onClick={p.onClose}>Cerrar y actualizar</button></fieldset>;}
