import {useState} from 'react';
import {useDepartments,useDepartmentEdit} from './useDepartments';
import type {Department} from './departmentAdminApi';
import {DepartmentCreation} from './DepartmentCreation';
type Props={base:string;token:string;companyId:string;branchId:string;canEdit:boolean};
export function DepartmentsPanel(p:Props){const s=useDepartments(p.base,p.token,p.companyId,p.branchId),[selected,setSelected]=useState<Department|null>(null);const close=()=>{setSelected(null);s.refresh();};
 return <section className="panel"><h2>Departamentos de tu sucursal</h2>{p.canEdit&&<DepartmentCreation {...p} onCreated={()=>s.refresh()}/>}<label>Nombre o código<input maxLength={100} value={s.search} onChange={e=>s.setSearch(e.target.value)}/></label><label>Estado<select value={s.status} onChange={e=>s.setStatus(e.target.value)}><option value="">Todos</option><option value="ACTIVE">Activos</option><option value="INACTIVE">Inactivos</option></select></label><button disabled={s.loading} onClick={s.apply}>Buscar</button>{s.loading&&<p>Consultando…</p>}{s.error&&<p role="alert">{s.error}</p>}{selected&&<Edit key={selected.id} {...p} row={selected} onClose={close}/>} {!s.loading&&!s.error&&!s.page.items.length&&<p>No hay departamentos para esta búsqueda.</p>}{s.page.items.map(row=><article key={row.id}><strong>{row.name}</strong><p>{row.code} · {row.status==='ACTIVE'?'Activo':'Inactivo'}</p>{p.canEdit&&<button disabled={!!selected} onClick={()=>setSelected({...row})}>Editar departamento</button>}</article>)}<p>Página {s.pageNumber} · Hasta 20 registros</p><button disabled={s.loading||s.pageNumber===1} onClick={s.previous}>Anterior</button><button disabled={s.loading||!!s.error||!s.page.nextCursor} onClick={s.next}>Siguiente</button><button disabled={s.loading} onClick={s.refresh}>Actualizar departamentos</button></section>;
}
function Edit({base,token,row,onClose}:{base:string;token:string;row:Department;onClose:()=>void}){const s=useDepartmentEdit(base,token,row,onClose),locked=s.busy||s.blocked;return <fieldset><legend>Editar {row.name}</legend><label>Nombre<input disabled={locked} maxLength={120} value={s.name} onChange={e=>s.setName(e.target.value)}/></label><label>Código<input disabled={locked} maxLength={32} value={s.code} onChange={e=>s.setCode(e.target.value)}/></label><label>Estado<select disabled={locked} value={s.status} onChange={e=>s.setStatus(e.target.value as Department['status'])}><option value="ACTIVE">Activo</option><option value="INACTIVE">Inactivo</option></select></label><p>Para desactivar, primero reasigna o desactiva sus empleados activos. Se conserva el historial.</p>{s.error&&<p role="alert">{s.error}</p>}<button disabled={!s.ready} onClick={()=>{if(window.confirm(`Guardar departamento ${s.name.trim()} (${s.code.trim().toUpperCase()}), ${s.status==='ACTIVE'?'activo':'inactivo'}?`))void s.save();}}>Guardar departamento</button><button disabled={s.busy} onClick={onClose}>Cerrar y actualizar</button></fieldset>;}
