import {EmployeeDepartment} from './EmployeeDepartment';
import {EmployeeStatus} from './EmployeeStatus';
import {EmployeeEdit} from './EmployeeEdit';
import {EmployeeCreation} from './EmployeeCreation';
import {useEmployees} from './useEmployees';
export function EmployeePanel({base,token,companyId,branchId,canCreate,canManageDepartments,canEdit}:{base:string;token:string;companyId:string;branchId:string;canCreate:boolean;canManageDepartments:boolean;canEdit:boolean}){
 const s=useEmployees(base,token,companyId,branchId);
 return <section className="panel"><h2>Empleados de tu sucursal</h2>{canCreate&&<EmployeeCreation key={token} canManageDepartments={canManageDepartments} base={base} token={token} companyId={companyId} branchId={branchId} onSaved={s.refresh} />}<label>Nombre o puesto<input maxLength={100} value={s.search} onChange={e=>s.setSearch(e.target.value)}/></label><label>Estado<select value={s.status} onChange={e=>s.setStatus(e.target.value)}><option value="">Todos</option><option value="ACTIVE">Activos</option><option value="INACTIVE">Inactivos</option></select></label><button disabled={s.loading} onClick={s.apply}>Buscar</button>{s.loading&&<p>Consultando…</p>}{s.error&&<p role="alert">{s.error}</p>}{!s.loading&&!s.error&&!s.page.items.length&&<p>No hay empleados para esta consulta.</p>}{s.page.items.map(row=><article key={row.id}><strong>{row.fullName}</strong><p>{row.position} · {row.status==='ACTIVE'?'Activo':'Inactivo'}</p><p>Departamento: {row.departmentId}</p>{canEdit&&<EmployeeEdit base={base} token={token} employee={row} onSaved={s.refresh} />}{canEdit&&<EmployeeStatus base={base} token={token} employee={row} onSaved={s.refresh} />}{canEdit&&<EmployeeDepartment base={base} token={token} employee={row} onSaved={s.refresh} />}</article>)}<p>Página {s.pageNumber} · Hasta 20 empleados por página</p><button disabled={s.loading||s.pageNumber===1} onClick={s.previous}>Anterior</button><button disabled={s.loading||!!s.error||!s.page.nextCursor} onClick={s.next}>Siguiente</button><button disabled={s.loading} onClick={s.refresh}>Actualizar</button></section>;
}
