import { useEffect,useRef,useState,type FormEvent } from 'react';
import {financePage,type FinanceAccount,type CashEntry} from './financeApi';
import {requestData} from './webApi';
import {validateAccount,validateCashMovement} from './financeValidation';
function FinancialList({apiUrl,token,kind,disabled,onSelect,selected}:{apiUrl:string;token:string;kind:'bank-accounts'|'cash-movements';disabled:boolean;onSelect?:(row:FinanceAccount)=>void;selected?:FinanceAccount|null}) {
 const [rows,setRows]=useState<(FinanceAccount|CashEntry)[]>([]),[search,setSearch]=useState(''),[applied,setApplied]=useState(''),[type,setType]=useState(''),[cursors,setCursors]=useState(['']),[next,setNext]=useState<string|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[revision,setRevision]=useState(0);const cursor=cursors[cursors.length-1];
 useEffect(()=>{const c=new AbortController();setLoading(true);setError('');setRows([]);setNext(null);financePage(apiUrl,token,kind,c.signal,applied,cursor,type).then(page=>{if(!c.signal.aborted){setRows(page.items);setNext(page.nextCursor);}}).catch(e=>{if(!c.signal.aborted)setError(e instanceof Error?e.message:'No se pudo consultar.');}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[apiUrl,token,kind,applied,cursor,type,revision]);
 const locked=disabled||loading;
 return <section className="panel"><h3>{kind==='bank-accounts'?'Cuentas de la sucursal':'Movimientos de caja'}</h3>{selected&&<p>Seleccionada: {selected.name}</p>}<form onSubmit={e=>{e.preventDefault();setApplied(search.trim());setCursors(['']);setRevision(v=>v+1);}}><div className="field"><label htmlFor={kind+'-search'}>Buscar {kind==='bank-accounts'?'nombre, banco o identificador':'concepto o fecha'}</label><input id={kind+'-search'} value={search} maxLength={100} disabled={disabled} onChange={e=>setSearch(e.target.value)}/></div><button disabled={locked}>Buscar</button><button type="button" disabled={locked} onClick={()=>{setSearch('');setApplied('');setCursors(['']);setRevision(v=>v+1);}}>Ver todos</button></form>{kind==='cash-movements'&&<div className="field"><label htmlFor="cash-type-filter">Tipo de movimiento</label><select id="cash-type-filter" value={type} disabled={disabled} onChange={e=>{setType(e.target.value);setCursors(['']);}}><option value="">Todos</option><option value="INFLOW">Entradas</option><option value="OUTFLOW">Salidas</option></select></div>}{loading?<p>Consultando…</p>:error?<p role="alert" className="error-box">{error}</p>:<><p>Página {cursors.length} · {rows.length} registros</p>{!rows.length&&<p>No hay registros para esta búsqueda.</p>}<div className="data-list">{rows.map(row=><div className="data-row" key={row.id}>{'name' in row?<><span><strong>{row.name}</strong><small>{row.bankName} · {row.status==='ACTIVE'?'Activa':'Inactiva'}</small></span>{onSelect&&<button disabled={disabled||row.status!=='ACTIVE'} onClick={()=>onSelect(row)}>{selected?.id===row.id?'Seleccionada':'Seleccionar'}</button>}</>:<><span><strong>{row.concept}</strong><small>{row.type==='INFLOW'?'Entrada':'Salida'} · {row.date}</small></span><strong>{row.amount.toLocaleString('es-MX')}</strong></>}</div>)}</div></>}<div style={{display:'flex',gap:12,marginTop:16}}><button disabled={locked||cursors.length===1} onClick={()=>setCursors(v=>v.slice(0,-1))}>Anterior</button><button disabled={locked||!next} onClick={()=>{if(next)setCursors(v=>[...v,next]);}}>Siguiente</button><button disabled={locked} onClick={()=>{setCursors(['']);setRevision(v=>v+1);}}>{error?'Reintentar':'Actualizar'}</button></div></section>;
}
export function FinancePanel({apiUrl,token,canCreate}:{apiUrl:string;token:string;canCreate:boolean}) {
 const [selected,setSelected]=useState<FinanceAccount|null>(null),[revision,setRevision]=useState(0),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [account,setAccount]=useState({name:'',bankName:'',iban:''}),[cash,setCash]=useState({accountId:'',concept:'',type:'INFLOW',amount:'',date:''});const write=useRef<AbortController|null>(null);useEffect(()=>()=>write.current?.abort(),[]);
 async function save(event:FormEvent,kind:'account'|'cash') {
  event.preventDefault();if(write.current||!canCreate)return;setError('');setNotice('');let payload:Record<string,string|number>;
  try{payload=kind==='account'?validateAccount(account):validateCashMovement(cash,selected?[selected]:[]);}catch(e){setError(e instanceof Error?e.message:'Revisa los datos.');return;}
  if(!window.confirm(kind==='account'?`Crear cuenta: ${payload.name} · ${payload.bankName}`:`Registrar ${payload.type==='INFLOW'?'entrada':'salida'}: ${payload.amount} · ${payload.concept} · ${payload.date} en ${selected?.name}.`))return;
  const c=new AbortController();write.current=c;setSaving(true);
  try{const data=await requestData(apiUrl,kind==='account'?'/bank-accounts':'/cash-movements',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify(payload),signal:c.signal});if(!data||typeof data!=='object'||!('id' in data)||typeof data.id!=='string'||!/^[a-f0-9]{24}$/i.test(data.id)||kind==='account'&&(!('status' in data)||data.status!=='ACTIVE')||Object.entries(payload).some(([key,value])=>(data as Record<string,unknown>)[key]!==value))throw new Error('No se pudo confirmar el guardado. Actualiza antes de reintentar.');if(c.signal.aborted)return;setAccount({name:'',bankName:'',iban:''});setCash({accountId:'',concept:'',type:'INFLOW',amount:'',date:''});setSelected(null);setNotice('Registro confirmado.');setRevision(v=>v+1);}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:'No se pudo confirmar el guardado. Actualiza antes de reintentar.');}finally{write.current=null;if(!c.signal.aborted)setSaving(false);}
 }
 return <><FinancialList key={'accounts'+revision} apiUrl={apiUrl} token={token} kind="bank-accounts" disabled={saving} selected={selected} onSelect={canCreate?row=>{setSelected(row);setCash(v=>({...v,accountId:row.id}));}:undefined}/>{canCreate&&<section className="panel"><h3>Registrar en Finanzas</h3><p>Los importes registrados no representan saldos bancarios. El identificador de cuenta no se certifica desde esta pantalla.</p><form onSubmit={e=>void save(e,'account')}><fieldset disabled={saving}><legend>Nueva cuenta</legend>{(['name','bankName','iban'] as const).map(field=><div className="field" key={field}><label htmlFor={'account-'+field}>{field==='name'?'Nombre':field==='bankName'?'Banco':'Identificador bancario'}</label><input id={'account-'+field} required maxLength={field==='iban'?34:100} value={account[field]} onChange={e=>setAccount(v=>({...v,[field]:e.target.value}))}/></div>)}<button className="primary-button">Revisar y crear cuenta</button></fieldset></form><form onSubmit={e=>void save(e,'cash')}><fieldset disabled={saving}><legend>Movimiento de caja</legend><p>Cuenta seleccionada: {selected?.name??'Selecciona una cuenta arriba'}</p><div className="field"><label htmlFor="cash-type">Tipo</label><select id="cash-type" value={cash.type} onChange={e=>setCash(v=>({...v,type:e.target.value}))}><option value="INFLOW">Entrada</option><option value="OUTFLOW">Salida</option></select></div>{(['concept','amount','date'] as const).map(field=><div className="field" key={field}><label htmlFor={'cash-'+field}>{field==='concept'?'Concepto':field==='amount'?'Importe':'Fecha'}</label><input id={'cash-'+field} required type={field==='amount'?'number':field==='date'?'date':'text'} min={field==='amount'?'0.01':undefined} step={field==='amount'?'0.01':undefined} maxLength={field==='concept'?200:undefined} value={cash[field]} onChange={e=>setCash(v=>({...v,[field]:e.target.value}))}/></div>)}<button className="primary-button" disabled={!selected}>Revisar y registrar movimiento</button></fieldset></form></section>}{error&&<p className="error-box" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<FinancialList key={'cash'+revision} apiUrl={apiUrl} token={token} kind="cash-movements" disabled={saving}/></>;
}
