import {useState} from 'react';import {useMaintenanceForm} from './useMaintenanceForm';import type {MaintenanceOrder} from './maintenanceApi';
import {DocumentExportButtons} from './DocumentExportButtons';import {maintenanceDocument} from './operationsDocument';
import {useMaintenance} from './useMaintenance';
type Props={base:string;token:string;companyId:string;branchId:string;canManage:boolean};
const labels:Record<string,string>={scheduled:'Programado',in_progress:'En curso',completed:'Terminado',cancelled:'Cancelado',low:'Baja',medium:'Media',high:'Alta'};
export function MaintenancePanel(p:Props){const s=useMaintenance(p.base,p.token,p.companyId,p.branchId),[form,setForm]=useState<MaintenanceOrder|'new'|null>(null);const close=()=>{setForm(null);s.refresh();};return <section className="panel"><h2>Mantenimiento de tu sucursal</h2><p>Órdenes de trabajo registradas en tu sucursal. El equipo se identifica por nombre.</p>{p.canManage&&<button disabled={!!form} onClick={()=>setForm('new')}>Nueva orden</button>}{form&&<Form key={form==='new'?'new':form.id} {...p} original={form==='new'?undefined:form} onClose={close}/>}<label>Buscar equipo o trabajo<input maxLength={100} value={s.search} onChange={e=>s.setSearch(e.target.value)}/></label><label>Estado<select value={s.status} onChange={e=>s.setStatus(e.target.value)}><option value="">Todos</option>{['scheduled','in_progress','completed','cancelled'].map(v=><option key={v} value={v}>{labels[v]}</option>)}</select></label><button disabled={s.loading} onClick={s.apply}>Buscar</button>{s.loading&&<p>Consultando…</p>}{s.error&&<p role="alert">{s.error}</p>}{!s.loading&&!s.error&&!s.page.items.length&&<p>No hay registros para esta búsqueda.</p>}{s.page.items.map(r=><article key={r.id}><h3>{r.assetName}</h3><p>{r.description}</p><p>{r.scheduledDate} · {labels[r.priority]} · {labels[r.status]}</p>{r.completionNote&&<p>Resultado: {r.completionNote}</p>}<DocumentExportButtons document={maintenanceDocument(r)}/>{p.canManage&&['scheduled','in_progress'].includes(r.status)&&<button disabled={!!form} onClick={()=>setForm({...r})}>Cambiar estado</button>}</article>)}<p>Página {s.pageNumber}</p><button disabled={s.loading||s.pageNumber===1} onClick={s.previous}>Anterior</button><button disabled={s.loading||!!s.error||!s.page.nextCursor} onClick={s.next}>Siguiente</button><button disabled={s.loading} onClick={s.refresh}>Actualizar</button></section>;}


function Form(p:Props&{original?:MaintenanceOrder;onClose:()=>void}){const s=useMaintenanceForm(p.base,p.token,p.companyId,p.branchId,p.onClose,p.original),locked=s.busy||s.blocked;return <fieldset><legend>{p.original?'Estado del mantenimiento':'Nueva orden'}</legend>{p.original?<><p>{p.original.assetName} · {p.original.description}</p><label>Estado<select disabled={locked} value={s.status} onChange={e=>s.setStatus(e.target.value as MaintenanceOrder['status'])}><option value={p.original.status==='scheduled'?'in_progress':'completed'}>{p.original.status==='scheduled'?'En curso':'Terminado'}</option><option value="cancelled">Cancelado</option></select></label>{s.status==='completed'&&<label>Resultado del trabajo<textarea disabled={locked} maxLength={1000} value={s.completionNote} onChange={e=>s.setCompletionNote(e.target.value)}/></label>}<p>Terminado y cancelado son estados finales.</p></>:<><label>Equipo<input disabled={locked} maxLength={120} value={s.assetName} onChange={e=>s.setAssetName(e.target.value)}/></label><label>Trabajo<textarea disabled={locked} maxLength={1000} value={s.description} onChange={e=>s.setDescription(e.target.value)}/></label><label>Fecha programada<input disabled={locked} type="date" value={s.scheduledDate} onChange={e=>s.setScheduledDate(e.target.value)}/></label><label>Prioridad<select disabled={locked} value={s.priority} onChange={e=>s.setPriority(e.target.value as MaintenanceOrder['priority'])}>{['low','medium','high'].map(v=><option key={v} value={v}>{labels[v]}</option>)}</select></label></>}{s.error&&<p role="alert">{s.error}</p>}<button disabled={!s.ready} onClick={()=>{if(window.confirm(p.original?'Cambiar mantenimiento de '+p.original.assetName+' a '+labels[s.status]+'?':'Crear mantenimiento de '+s.assetName.trim()+' para '+s.scheduledDate+'?'))void s.save();}}>Guardar orden</button><button disabled={s.busy} onClick={p.onClose}>Cerrar y actualizar</button></fieldset>;}
