import {DocumentExportButtons} from './DocumentExportButtons';
import {useEffect,useState} from 'react';
import {requestData} from './webApi';
export function PeriodReport({apiUrl,token,companyId,branchId}:{apiUrl:string;token:string;companyId:string;branchId:string}){
 const [type,setType]=useState('sales'),[period,setPeriod]=useState('month'),[data,setData]=useState<{from:string;to:string;metrics:Record<string,number>}|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{const c=new AbortController();setLoading(true);setData(null);setError('');requestData(apiUrl,'/reports/preview?'+new URLSearchParams({type,period}),{headers:{Authorization:'Bearer '+token},signal:c.signal}).then(value=>{const v=value as any;const keys=type==='sales'?['total','orders','units']:['income','expenses','balance','incomeEntries','expenseEntries'];if(!v||v.companyId!==companyId||v.branchId!==branchId||v.type!==type||v.period!==period||v.timezone!=='UTC'||v.basis!==(type==='sales'?'createdAt':'movementDate')||!Number.isFinite(Date.parse(v.from))||!Number.isFinite(Date.parse(v.to))||keys.some(k=>typeof v.metrics?.[k]!=='number'||!Number.isFinite(v.metrics[k])))throw new Error('Respuesta de reporte inesperada.');if(!c.signal.aborted)setData(v);}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[apiUrl,token,companyId,branchId,type,period,revision]);
 const labels:Record<string,string>={total:'Ventas no canceladas',orders:'Operaciones',units:'Cantidad vendida',income:'Entradas de caja',expenses:'Salidas de caja',balance:'Flujo neto',incomeEntries:'Número de entradas',expenseEntries:'Número de salidas'};
 function exportCsv(){if(!data)return;const rows=[['Empresa',companyId],['Sucursal',branchId],['Periodo UTC',data.from+' a '+data.to],...Object.entries(data.metrics).map(([k,v])=>[labels[k]??k,String(v)])];const csv='\ufeff'+rows.map(r=>r.map(v=>'"'+v.replace(/"/g,'""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='nucleo-reporte-'+type+'-'+period+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="panel"><h2>Reporte por periodo</h2><div className="field"><label htmlFor="report-type">Tipo</label><select id="report-type" value={type} onChange={e=>setType(e.target.value)}><option value="sales">Ventas</option><option value="cash-flow">Flujo de caja</option></select></div><div className="field"><label htmlFor="report-period">Periodo actual en UTC</label><select id="report-period" value={period} onChange={e=>setPeriod(e.target.value)}>{[['day','Día'],['week','Semana desde lunes'],['month','Mes'],['quarter','Trimestre'],['year','Año']].map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></div><button disabled={loading} onClick={()=>setRevision(v=>v+1)}>Actualizar</button><button disabled={!data||loading} onClick={exportCsv}>Exportar CSV</button>{loading?<p>Consultando…</p>:error?<p role="alert">{error}</p>:data&&<><DocumentExportButtons document={{title:type==='sales'?'Reporte de ventas':'Reporte de flujo de caja',company:companyId,branch:branchId,note:data.from+' a '+data.to+' (UTC). Moneda no informada; ventas excluye canceladas; caja no representa utilidad ni saldo bancario.',columns:['Indicador','Valor'],rows:Object.entries(data.metrics).map(([key,value])=>[labels[key]??key,value])}}/><p>{data.from} a {data.to} (UTC)</p>{Object.entries(data.metrics).map(([key,value])=><p key={key}>{labels[key]??key}: <strong>{value.toLocaleString('es-MX',{maximumFractionDigits:6})}</strong></p>)}</>}<p>Ventas usa fecha de registro y excluye canceladas. Caja usa la fecha del movimiento, incluyendo el día actual. Moneda no informada. Este reporte no representa utilidad ni saldo bancario.</p></section>;
}
