import {ApiError,requestData} from './webApi';
export type Project={id:string;companyId:string;branchId:string;customerId:string;customerName?:string;name:string;startDate:string;endDate:string;status:'ACTIVE'|'PAUSED'|'CLOSED';progress:number};
export type ProjectCustomer={id:string;name:string;companyId:string;branchId:string;status:'ACTIVE'};
export const projectDate=(v:string)=>{const d=new Date(v+'T00:00:00Z');return /^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(d.getTime())&&d.toISOString().slice(0,10)===v;};
function valid(row:any,co:string,br:string):row is Project{return !!row&&(row.customerName===undefined||(typeof row.customerName==='string'&&row.customerName.trim().length>0&&row.customerName.length<=120))&&/^[a-f0-9]{24}$/i.test(row.id)&&row.companyId===co&&row.branchId===br&&/^[a-f0-9]{24}$/i.test(row.customerId)&&typeof row.name==='string'&&row.name.trim().length>=2&&row.name.length<=120&&typeof row.startDate==='string'&&typeof row.endDate==='string'&&projectDate(row.startDate)&&projectDate(row.endDate)&&row.endDate>=row.startDate&&['ACTIVE','PAUSED','CLOSED'].includes(row.status)&&typeof row.progress==='number'&&Number.isFinite(row.progress)&&row.progress>=0&&row.progress<=100;}
export async function projectPage(base:string,token:string,co:string,br:string,search:string,status:string,cursor?:string,signal?:AbortSignal){const q=new URLSearchParams({search:search.trim(),limit:'20'});if(status)q.set('status',status);if(cursor)q.set('cursor',cursor);const raw:any=await requestData(base,'/projects/page?'+q,{headers:{Authorization:'Bearer '+token},signal});const fail=()=>new ApiError('No se pudo confirmar la página de proyectos.');if(!raw||!Array.isArray(raw.items)||raw.items.length>20||!(raw.nextCursor===null||typeof raw.nextCursor==='string'))throw fail();let previous=cursor;for(const row of raw.items){if(!valid(row,co,br)||(status&&row.status!==status)||(previous&&row.id>=previous))throw fail();previous=row.id;}if(raw.nextCursor!==null&&(raw.items.length!==20||raw.nextCursor!==raw.items[19].id))throw fail();return raw as {items:Project[];nextCursor:string|null};}
export async function projectCustomers(base:string,token:string,co:string,br:string,search:string,cursor?:string,signal?:AbortSignal){const q=new URLSearchParams({search:search.trim(),limit:'20'});if(cursor)q.set('cursor',cursor);const raw:any=await requestData(base,'/projects/customer-options?'+q,{headers:{Authorization:'Bearer '+token},signal});const fail=()=>new ApiError('No se pudo confirmar el selector de clientes.');if(!raw||!Array.isArray(raw.items)||raw.items.length>20||!(raw.nextCursor===null||typeof raw.nextCursor==='string'))throw fail();let previous=cursor;for(const row of raw.items){if(!row||!/^[a-f0-9]{24}$/i.test(row.id)||typeof row.name!=='string'||!row.name.trim()||row.companyId!==co||row.branchId!==br||row.status!=='ACTIVE'||(previous&&row.id>=previous))throw fail();previous=row.id;}if(raw.nextCursor!==null&&(raw.items.length!==20||raw.nextCursor!==raw.items[19].id))throw fail();return raw as {items:ProjectCustomer[];nextCursor:string|null};}
export async function saveProject(base:string,token:string,co:string,br:string,input:{name:string;startDate:string;endDate:string;customerId?:string;status?:Project['status'];progress?:number},original?:Project,signal?:AbortSignal):Promise<Project>{const name=input.name.trim();if(name.length<2||name.length>120||!projectDate(input.startDate)||!projectDate(input.endDate)||input.endDate<input.startDate||(!original&&!/^[a-f0-9]{24}$/i.test(input.customerId??''))||(original&&(!['ACTIVE','PAUSED','CLOSED'].includes(input.status??'')||!Number.isFinite(input.progress)||input.progress!<0||input.progress!>100||(input.status==='CLOSED'&&input.progress!==100))))throw new ApiError('Revisa nombre, cliente, fechas y avance. Para cerrar, el avance debe ser 100%.',400);
 const body=original?{name,startDate:input.startDate,endDate:input.endDate,status:input.status,progress:input.progress,expected:{name:original.name,startDate:original.startDate,endDate:original.endDate,status:original.status,progress:original.progress}}:{name,startDate:input.startDate,endDate:input.endDate,customerId:input.customerId};let raw:any;try{raw=await requestData(base,'/projects'+(original?'/'+encodeURIComponent(original.id):''),{method:original?'PATCH':'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify(body),signal});}catch(e){if(e instanceof ApiError&&e.status===409)throw new ApiError('El proyecto cambió. Cierra y actualiza la lista.',409);throw e;}
 if(!valid(raw,co,br)||raw.name!==name||raw.startDate!==input.startDate||raw.endDate!==input.endDate||raw.customerId!==(original?.customerId??input.customerId)||raw.status!==(original?input.status:'ACTIVE')||raw.progress!==(original?input.progress:0)||(original&&raw.id!==original.id))throw new ApiError('No se pudo confirmar el proyecto. Consulta la lista antes de reintentar.');return raw;}
