import {useState} from 'react';import {useQualityForm} from './useQualityForm';import type {QualityInspection} from './qualityApi';
import {DocumentExportButtons} from './DocumentExportButtons';import {qualityDocument} from './operationsDocument';
import {useQuality} from './useQuality';
type Props={base:string;token:string;companyId:string;branchId:string;canManage:boolean};
const labels:Record<string,string>={scheduled:'Programado',in_progress:'En curso',completed:'Terminado',cancelled:'Cancelado',low:'Baja',medium:'Media',high:'Alta'};
const results:Record<string,string>={pass:'Aprobado',watch:'Con observaciones',fail:'Rechazado'};
export function QualityPanel(p:Props){const s=useQuality(p.base,p.token,p.companyId,p.branchId),[form,setForm]=useState<QualityInspection|'new'|null>(null);const close=()=>{setForm(null);s.refresh();};return <section className="panel"><h2>Calidad de tu sucursal</h2><p>Inspecciones registradas en tu sucursal. Los resultados no modifican existencias.</p>{p.canManage&&<button disabled={!!form} onClick={()=>setForm('new')}>Nueva inspección</button>}{form&&<Form key={form==='new'?'new':form.id} {...p} original={form==='new'?undefined:form} onClose={close}/>}<label>Buscar equipo o trabajo<input maxLength={100} value={s.search} onChange={e=>s.setSearch(e.target.value)}/></label><label>Estado<select value={s.status} onChange={e=>s.setStatus(e.target.value)}><option value="">Todos</option>{['scheduled','in_progress','completed','cancelled'].map(v=><option key={v} value={v}>{labels[v]}</option>)}</select></label><button disabled={s.loading} onClick={s.apply}>Buscar</button>{s.loading&&<p>Consultando…</p>}{s.error&&<p role="alert">{s.error}</p>}{!s.loading&&!s.error&&!s.page.items.length&&<p>No hay registros para esta búsqueda.</p>}{s.page.items.map(r=><article key={r.id}><h3>{r.subject}</h3><p>{r.criteria}</p><p>{r.inspectionDate} · {labels[r.priority]} · {labels[r.status]}</p>{r.result&&<p>{results[r.result]}</p>}{r.completionNote&&<p>Resultado: {r.completionNote}</p>}<DocumentExportButtons document={qualityDocument(r)}/>{p.canManage&&['scheduled','in_progress'].includes(r.status)&&<button disabled={!!form} onClick={()=>setForm({...r})}>Cambiar estado</button>}</article>)}<p>Página {s.pageNumber}</p><button disabled={s.loading||s.pageNumber===1} onClick={s.previous}>Anterior</button><button disabled={s.loading||!!s.error||!s.page.nextCursor} onClick={s.next}>Siguiente</button><button disabled={s.loading} onClick={s.refresh}>Actualizar</button></section>;}


function Form(p:Props&{original?:QualityInspection;onClose:()=>void}){const s=useQualityForm(p.base,p.token,p.companyId,p.branchId,p.onClose,p.original),locked=s.busy||s.blocked;return <fieldset><legend>{p.original?'Estado de inspección':'Nueva inspección'}</legend>{p.original?<><p>{p.original.subject} · {p.original.criteria}</p><label>Estado<select disabled={locked} value={s.status} onChange={e=>s.setStatus(e.target.value as QualityInspection['status'])}><option value={p.original.status==='scheduled'?'in_progress':'completed'}>{p.original.status==='scheduled'?'En curso':'Terminado'}</option><option value="cancelled">Cancelado</option></select></label>{s.status==='completed'&&<><label>Resultado<select disabled={locked} value={s.result} onChange={e=>s.setResult(e.target.value as ''|'pass'|'watch'|'fail')}><option value="">Selecciona un resultado</option>{Object.entries(results).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label><label>Observaciones del resultado<textarea disabled={locked} maxLength={1000} value={s.completionNote} onChange={e=>s.setCompletionNote(e.target.value)}/></label></>}<p>Terminado y cancelado son estados finales.</p></>:<><label>Objeto revisado<input disabled={locked} maxLength={120} value={s.subject} onChange={e=>s.setSubject(e.target.value)}/></label><label>Criterios<textarea disabled={locked} maxLength={1000} value={s.criteria} onChange={e=>s.setCriteria(e.target.value)}/></label><label>Fecha de inspección<input disabled={locked} type="date" value={s.inspectionDate} onChange={e=>s.setInspectionDate(e.target.value)}/></label><label>Prioridad<select disabled={locked} value={s.priority} onChange={e=>s.setPriority(e.target.value as QualityInspection['priority'])}>{['low','medium','high'].map(v=><option key={v} value={v}>{labels[v]}</option>)}</select></label></>}{s.error&&<p role="alert">{s.error}</p>}<button disabled={!s.ready} onClick={()=>{if(window.confirm(p.original?'Cambiar inspección de '+p.original.subject+' a '+labels[s.status]+'?':'Crear inspección de '+s.subject.trim()+' para '+s.inspectionDate+'?'))void s.save();}}>Guardar inspección</button><button disabled={s.busy} onClick={p.onClose}>Cerrar y actualizar</button></fieldset>;}
