import {useState} from 'react';import {useRiskForm} from './useRiskForm';import type {RiskRecord} from './riskApi';
import {DocumentExportButtons} from './DocumentExportButtons';import {riskDocument} from './operationsDocument';
import {useRisks} from './useRisks';
type Props={base:string;token:string;companyId:string;branchId:string;canManage:boolean};
const labels:Record<string,string>={identified:'Identificado',mitigating:'En mitigación',closed:'Cerrado',dismissed:'Descartado',low:'Bajo',medium:'Medio',high:'Alto'};
export function RisksPanel(p:Props){const s=useRisks(p.base,p.token,p.companyId,p.branchId),[form,setForm]=useState<RiskRecord|'new'|null>(null),[editDetails,setEditDetails]=useState(false);const close=()=>{setForm(null);setEditDetails(false);s.refresh();};return <section className="panel"><h2>Riesgos de tu sucursal</h2><p>Riesgos registrados en tu sucursal con nivel cualitativo y plan de mitigación.</p>{p.canManage&&<button disabled={!!form} onClick={()=>setForm('new')}>Nuevo riesgo</button>}{form&&<Form key={(form==='new'?'new':form.id)+(editDetails?':edit':':status')} {...p} original={form==='new'?undefined:form} editDetails={editDetails} onClose={close}/>}<label>Buscar riesgo o plan de mitigación<input maxLength={100} value={s.search} onChange={e=>s.setSearch(e.target.value)}/></label><label>Estado<select value={s.status} onChange={e=>s.setStatus(e.target.value)}><option value="">Todos</option>{['identified','mitigating','closed','dismissed'].map(v=><option key={v} value={v}>{labels[v]}</option>)}</select></label><button disabled={s.loading} onClick={s.apply}>Buscar</button>{s.loading&&<p>Consultando…</p>}{s.error&&<p role="alert">{s.error}</p>}{!s.loading&&!s.error&&!s.page.items.length&&<p>No hay registros para esta búsqueda.</p>}{s.page.items.map(r=><article key={r.id}><h3>{r.name}</h3><p>{r.mitigationPlan}</p><p>{r.reviewDate} · {labels[r.level]} · {labels[r.status]}</p>{r.completionNote&&<p>Resultado: {r.completionNote}</p>}<DocumentExportButtons document={riskDocument(r)}/>{p.canManage&&['identified','mitigating'].includes(r.status)&&<button disabled={!!form} onClick={()=>setForm({...r})}>Cambiar estado</button>}{p.canManage&&['identified','mitigating'].includes(r.status)&&<button disabled={!!form} onClick={()=>{setEditDetails(true);setForm({...r});}}>Editar plan</button>}</article>)}<p>Página {s.pageNumber}</p><button disabled={s.loading||s.pageNumber===1} onClick={s.previous}>Anterior</button><button disabled={s.loading||!!s.error||!s.page.nextCursor} onClick={s.next}>Siguiente</button><button disabled={s.loading} onClick={s.refresh}>Actualizar</button></section>;}


function Form(p:Props&{original?:RiskRecord;editDetails?:boolean;onClose:()=>void}){const s=useRiskForm(p.base,p.token,p.companyId,p.branchId,p.onClose,p.original,undefined,p.editDetails),locked=s.busy||s.blocked;return <fieldset><legend>{p.editDetails?'Editar plan del riesgo':p.original?'Estado del riesgo':'Nuevo riesgo'}</legend>{p.original&&!p.editDetails?<><p>{p.original.name} · {p.original.mitigationPlan}</p><label>Estado<select disabled={locked} value={s.status} onChange={e=>s.setStatus(e.target.value as RiskRecord['status'])}><option value={p.original.status==='identified'?'mitigating':'closed'}>{p.original.status==='identified'?'En mitigación':'Cerrado'}</option><option value="dismissed">Descartado</option></select></label>{s.status==='closed'&&<label>Conclusión<textarea disabled={locked} maxLength={1000} value={s.completionNote} onChange={e=>s.setCompletionNote(e.target.value)}/></label>}<p>Cerrado y descartado son estados finales.</p></>:<><label>Nombre del riesgo<input disabled={locked} maxLength={120} value={s.name} onChange={e=>s.setName(e.target.value)}/></label><label>Plan de mitigación<textarea disabled={locked} maxLength={1000} value={s.mitigationPlan} onChange={e=>s.setMitigationPlan(e.target.value)}/></label><label>Fecha de revisión<input disabled={locked} type="date" value={s.reviewDate} onChange={e=>s.setReviewDate(e.target.value)}/></label><label>Nivel<select disabled={locked} value={s.level} onChange={e=>s.setLevel(e.target.value as RiskRecord['level'])}>{['low','medium','high'].map(v=><option key={v} value={v}>{labels[v]}</option>)}</select></label></>}{s.error&&<p role="alert">{s.error}</p>}<button disabled={!s.ready} onClick={()=>{if(window.confirm(p.editDetails?'Actualizar el plan de '+s.name.trim()+'?':p.original?'Cambiar riesgo de '+p.original.name+' a '+labels[s.status]+'?':'Crear riesgo de '+s.name.trim()+' para '+s.reviewDate+'?'))void s.save();}}>Guardar riesgo</button><button disabled={s.busy} onClick={p.onClose}>Cerrar y actualizar</button></fieldset>;}
