import {CatalogAdmin} from './CatalogAdmin';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {CatalogSelector} from './CatalogSelector';
import type {CatalogEntry} from './catalogApi';
import {WarehouseSelector} from './WarehouseSelector';
import {StockBalances} from './StockBalances';
import {StockHistory} from './StockHistory';
import {createStockRequest,createWarehouseRequest,validateStock,validateWarehouse,type WarehouseEntry,type StockKind} from './inventoryApi';
export function StockPanel({apiUrl,token,canCreate,onWarehouseCreated}:{apiUrl:string;token:string;canCreate:boolean;onWarehouseCreated:()=>void}) {
 const [product,setProduct]=useState<CatalogEntry|null>(null),[source,setSource]=useState<WarehouseEntry|null>(null),[destination,setDestination]=useState<WarehouseEntry|null>(null),[draft,setDraft]=useState({warehouseId:'',productId:'',destinationWarehouseId:'',quantity:'',reference:''}),[warehouseDraft,setWarehouseDraft]=useState({name:'',code:''}),[kind,setKind]=useState<StockKind>('receipts'),[saving,setSaving]=useState(false),[revision,setRevision]=useState(0),[warehouseRevision,setWarehouseRevision]=useState(0),[error,setError]=useState(''),[notice,setNotice]=useState('');const write=useRef<AbortController|null>(null);useEffect(()=>()=>write.current?.abort(),[]);
 async function submit(event:FormEvent,warehouse=false) {
  event.preventDefault();if(write.current||!canCreate)return;setError('');setNotice('');
  try{if(warehouse){validateWarehouse(warehouseDraft);if(!window.confirm('Crear almacén: '+warehouseDraft.name+' · '+warehouseDraft.code))return;}else{if(!product||!source||product.id!==draft.productId||source.id!==draft.warehouseId||product.status!=='ACTIVE'||source.status!=='ACTIVE'||kind==='transfers'&&(!destination||destination.id!==draft.destinationWarehouseId||destination.status!=='ACTIVE'))throw new Error('Selecciona producto y almacenes activos.');const payload=validateStock(kind,draft);if(!window.confirm(`${kind==='receipts'?'Entrada':kind==='issues'?'Salida':'Transferencia'}: ${product.name} · Cantidad: ${payload.quantity} · ${source.name}${kind==='transfers'?' → '+destination?.name:''} · Referencia: ${payload.reference}. Este movimiento modifica existencias.`))return;}}catch(e){setError(e instanceof Error?e.message:'Revisa los datos.');return;}
  const c=new AbortController();write.current=c;setSaving(true);
  try{if(warehouse){const row=await createWarehouseRequest(apiUrl,token,warehouseDraft,c.signal);if(c.signal.aborted)return;setSource(row);setDestination(null);setDraft(v=>({...v,warehouseId:row.id,destinationWarehouseId:''}));setWarehouseDraft({name:'',code:''});setWarehouseRevision(v=>v+1);setNotice('Almacén creado y seleccionado.');onWarehouseCreated();}else{await createStockRequest(apiUrl,token,kind,draft,c.signal);if(c.signal.aborted)return;setDraft(v=>({...v,quantity:'',reference:''}));setNotice('Movimiento registrado y confirmado.');}setRevision(v=>v+1);}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:'No se pudo confirmar el guardado. Revisa el historial antes de repetir.');}finally{write.current=null;if(!c.signal.aborted)setSaving(false);}
 }
 return <><section className="panel"><h3>Inventario</h3><p>Los saldos incluyen movimientos manuales y operaciones comerciales conjuntas confirmadas.</p>{canCreate&&<><form onSubmit={e=>void submit(e,true)}><fieldset disabled={saving}><legend>Nuevo almacén</legend>{(['name','code'] as const).map(field=><div className="field" key={field}><label htmlFor={'warehouse-'+field}>{field==='name'?'Nombre':'Código'}</label><input id={'warehouse-'+field} required minLength={2} maxLength={field==='name'?100:32} value={warehouseDraft[field]} onChange={e=>setWarehouseDraft(v=>({...v,[field]:e.target.value}))}/></div>)}<button className="primary-button">Revisar y crear almacén</button></fieldset></form><div className="field"><label htmlFor="stock-kind">Movimiento</label><select id="stock-kind" disabled={saving} value={kind} onChange={e=>setKind(e.target.value as StockKind)}><option value="receipts">Entrada</option><option value="issues">Salida</option><option value="transfers">Transferencia</option></select></div><CatalogSelector apiUrl={apiUrl} token={token} kind="products" label="Producto" selected={product} disabled={saving} onSelect={row=>{setProduct(row);setDraft(v=>({...v,productId:row.id}));}}/><WarehouseSelector key={'source'+warehouseRevision} apiUrl={apiUrl} token={token} label={kind==='receipts'?'Almacén de entrada':'Almacén de origen'} selected={source} disabled={saving} onSelect={row=>{setSource(row);setDraft(v=>({...v,warehouseId:row.id}));}}/>{kind==='transfers'&&<WarehouseSelector key={'destination'+warehouseRevision} apiUrl={apiUrl} token={token} label="Almacén destino" selected={destination} disabled={saving} onSelect={row=>{setDestination(row);setDraft(v=>({...v,destinationWarehouseId:row.id}));}}/>}<form onSubmit={e=>void submit(e)}><fieldset disabled={saving}><legend>Registrar movimiento</legend><div className="field"><label htmlFor="stock-quantity">Cantidad</label><input id="stock-quantity" required type="number" min="0.000001" step="0.000001" value={draft.quantity} onChange={e=>setDraft(v=>({...v,quantity:e.target.value}))}/></div><div className="field"><label htmlFor="stock-reference">Referencia única</label><input id="stock-reference" required maxLength={100} value={draft.reference} onChange={e=>setDraft(v=>({...v,reference:e.target.value}))}/></div><button className="primary-button" disabled={!source||!product}>{saving?'Guardando…':'Revisar y registrar'}</button></fieldset></form></>}{error&&<p role="alert" className="error-box">{error}</p>}{notice&&<p role="status">{notice}</p>}</section><CatalogAdmin apiUrl={apiUrl} token={token} kind="warehouses" canEdit={canCreate} disabled={saving} onChanged={()=>{setSource(null);setDestination(null);setDraft(v=>({...v,warehouseId:'',destinationWarehouseId:''}));setWarehouseRevision(v=>v+1);setRevision(v=>v+1);}}/><StockBalances key={'balances'+revision} apiUrl={apiUrl} token={token}/><StockHistory apiUrl={apiUrl} token={token} revision={revision}/></>;
}
