import {useState} from 'react';import {useTicketForm} from './useTicketForm';import type {SupportTicket} from './ticketApi';
import {DocumentExportButtons} from './DocumentExportButtons';import {ticketDocument} from './operationsDocument';
import {useTickets} from './useTickets';
type Props={base:string;token:string;companyId:string;branchId:string;canManage:boolean};
const labels:Record<string,string>={open:'Abierto',in_progress:'En curso',resolved:'Resuelto',cancelled:'Cancelado',low:'Baja',medium:'Media',high:'Alta'};
export function TicketsPanel(p:Props){const s=useTickets(p.base,p.token,p.companyId,p.branchId),[form,setForm]=useState<SupportTicket|'new'|null>(null);const close=()=>{setForm(null);s.refresh();};return <section className="panel"><h2>Mesa de ayuda de tu sucursal</h2><p>Tickets de soporte interno registrados en tu sucursal.</p>{p.canManage&&<button disabled={!!form} onClick={()=>setForm('new')}>Nuevo ticket</button>}{form&&<Form key={form==='new'?'new':form.id} {...p} original={form==='new'?undefined:form} onClose={close}/>}<label>Buscar asunto o descripción<input maxLength={100} value={s.search} onChange={e=>s.setSearch(e.target.value)}/></label><label>Estado<select value={s.status} onChange={e=>s.setStatus(e.target.value)}><option value="">Todos</option>{['open','in_progress','resolved','cancelled'].map(v=><option key={v} value={v}>{labels[v]}</option>)}</select></label><button disabled={s.loading} onClick={s.apply}>Buscar</button>{s.loading&&<p>Consultando…</p>}{s.error&&<p role="alert">{s.error}</p>}{!s.loading&&!s.error&&!s.page.items.length&&<p>No hay registros para esta búsqueda.</p>}{s.page.items.map(r=><article key={r.id}><h3>{r.subject}</h3><p>{r.description}</p><p>{r.targetDate} · {labels[r.priority]} · {labels[r.status]}</p>{r.completionNote&&<p>Resultado: {r.completionNote}</p>}<DocumentExportButtons document={ticketDocument(r)}/>{p.canManage&&['open','in_progress'].includes(r.status)&&<button disabled={!!form} onClick={()=>setForm({...r})}>Cambiar estado</button>}</article>)}<p>Página {s.pageNumber}</p><button disabled={s.loading||s.pageNumber===1} onClick={s.previous}>Anterior</button><button disabled={s.loading||!!s.error||!s.page.nextCursor} onClick={s.next}>Siguiente</button><button disabled={s.loading} onClick={s.refresh}>Actualizar</button></section>;}


function Form(p:Props&{original?:SupportTicket;onClose:()=>void}){const s=useTicketForm(p.base,p.token,p.companyId,p.branchId,p.onClose,p.original),locked=s.busy||s.blocked;return <fieldset><legend>{p.original?'Estado del soporte':'Nuevo ticket'}</legend>{p.original?<><p>{p.original.subject} · {p.original.description}</p><label>Estado<select disabled={locked} value={s.status} onChange={e=>s.setStatus(e.target.value as SupportTicket['status'])}><option value={p.original.status==='open'?'in_progress':'resolved'}>{p.original.status==='open'?'En curso':'Resuelto'}</option><option value="cancelled">Cancelado</option></select></label>{s.status==='resolved'&&<label>Resolución<textarea disabled={locked} maxLength={1000} value={s.completionNote} onChange={e=>s.setCompletionNote(e.target.value)}/></label>}<p>Resuelto y cancelado son estados finales.</p></>:<><label>Asunto<input disabled={locked} maxLength={120} value={s.subject} onChange={e=>s.setSubject(e.target.value)}/></label><label>Descripción<textarea disabled={locked} maxLength={1000} value={s.description} onChange={e=>s.setDescription(e.target.value)}/></label><label>Fecha objetivo<input disabled={locked} type="date" value={s.targetDate} onChange={e=>s.setTargetDate(e.target.value)}/></label><label>Prioridad<select disabled={locked} value={s.priority} onChange={e=>s.setPriority(e.target.value as SupportTicket['priority'])}>{['low','medium','high'].map(v=><option key={v} value={v}>{labels[v]}</option>)}</select></label></>}{s.error&&<p role="alert">{s.error}</p>}<button disabled={!s.ready} onClick={()=>{if(window.confirm(p.original?'Cambiar soporte de '+p.original.subject+' a '+labels[s.status]+'?':'Crear soporte de '+s.subject.trim()+' para '+s.targetDate+'?'))void s.save();}}>Guardar ticket</button><button disabled={s.busy} onClick={p.onClose}>Cerrar y actualizar</button></fieldset>;}
