import {useEffect,useRef,useState,type FormEvent} from 'react';
import {CatalogSelector} from './CatalogSelector';
import type {CatalogEntry} from './catalogApi';
import {createTransactionRequest,validateTransaction,type TransactionKind} from './transactionApi';
export function TransactionCreate({kind,apiUrl,token,onCreated}:{kind:TransactionKind;apiUrl:string;token:string;onCreated:()=>void}) {
 const [partner,setPartner]=useState<CatalogEntry|null>(null),[product,setProduct]=useState<CatalogEntry|null>(null),[draft,setDraft]=useState({partnerId:'',productId:'',quantity:'',unitCost:''}),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');const write=useRef<AbortController|null>(null);useEffect(()=>()=>write.current?.abort(),[]);
 async function submit(event:FormEvent) {
  event.preventDefault();if(write.current)return;setError('');setNotice('');
  try{if(!partner||!product||partner.id!==draft.partnerId||product.id!==draft.productId||partner.status!=='ACTIVE'||product.status!=='ACTIVE')throw new Error('Selecciona un contacto y producto activos.');const payload=validateTransaction(kind,draft);if(!window.confirm(`${kind==='sales'?'Crear venta':'Crear compra'}: ${partner.name} · ${product.name} · Cantidad: ${payload.quantity}. ${kind==='sales'?'El precio vigente lo determina el servidor.':'Costo unitario: '+draft.unitCost}. El registro inicia pendiente; inventario y caja se registran por separado.`))return;}catch(e){setError(e instanceof Error?e.message:'Revisa los datos.');return;}
  const c=new AbortController();write.current=c;setSaving(true);
  try{await createTransactionRequest(apiUrl,token,kind,draft,c.signal);if(c.signal.aborted)return;setDraft({partnerId:'',productId:'',quantity:'',unitCost:''});setPartner(null);setProduct(null);setNotice('Registro creado y confirmado.');onCreated();}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:'No se pudo confirmar el guardado. Revisa el listado antes de repetir.');}finally{write.current=null;if(!c.signal.aborted)setSaving(false);}
 }
 return <section className="panel"><h3>{kind==='sales'?'Nueva venta':'Nueva orden de compra'}</h3><CatalogSelector apiUrl={apiUrl} token={token} kind={kind==='sales'?'customers':'suppliers'} label={kind==='sales'?'Cliente':'Proveedor'} selected={partner} disabled={saving} onSelect={row=>{setPartner(row);setDraft(v=>({...v,partnerId:row.id}));}}/><CatalogSelector apiUrl={apiUrl} token={token} kind="products" label="Producto" selected={product} disabled={saving} onSelect={row=>{setProduct(row);setDraft(v=>({...v,productId:row.id}));}}/><form onSubmit={event=>void submit(event)}><fieldset disabled={saving} style={{border:0,padding:0}}><div className="field"><label htmlFor="transaction-quantity">Cantidad</label><input id="transaction-quantity" type="number" min="0.000001" step="0.000001" required value={draft.quantity} onChange={e=>setDraft(v=>({...v,quantity:e.target.value}))}/></div>{kind==='purchase-orders'&&<div className="field"><label htmlFor="transaction-cost">Costo unitario</label><input id="transaction-cost" type="number" min="0" step="0.01" required value={draft.unitCost} onChange={e=>setDraft(v=>({...v,unitCost:e.target.value}))}/></div>}{kind==='sales'&&<p>El precio y el total se calculan con el catálogo vigente del servidor.</p>}<button className="primary-button" disabled={!partner||!product}>{saving?'Guardando…':'Revisar y crear registro'}</button></fieldset></form>{error&&<p role="alert" className="error-box">{error}</p>}{notice&&<p role="status">{notice}</p>}</section>;
}
