import {ReceiptView} from './ReceiptView';
import {SettlementForm} from './SettlementForm';
import {useEffect,useRef,useState} from 'react';
import {catalogLookup} from './catalogApi';
import {transactionPageRequest,transactionStatusOptions,updateTransactionStatusRequest,type Transaction,type TransactionKind} from './transactionApi';
export function TransactionDirectory({apiUrl,token,kind,canEdit,externalRevision,companyId,branchId}:{apiUrl:string;token:string;kind:TransactionKind;canEdit:boolean;externalRevision:number;companyId:string;branchId:string}) {
 const [receipt,setReceipt]=useState<Transaction|null>(null);
 const [settling,setSettling]=useState<Transaction|null>(null);
 const [rows,setRows]=useState<Transaction[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[status,setStatus]=useState(''),[cursors,setCursors]=useState(['']),[next,setNext]=useState<string|null>(null),[revision,setRevision]=useState(0);
 const [names,setNames]=useState<Record<string,string>>({}),[nameError,setNameError]=useState('');
 const write=useRef<AbortController|null>(null),cursor=cursors[cursors.length-1];useEffect(()=>()=>write.current?.abort(),[]);
 useEffect(()=>{setCursors(['']);setRevision(v=>v+1);},[externalRevision]);
 useEffect(()=>{const c=new AbortController();setLoading(true);setError('');setRows([]);setNames({});setNameError('');setNext(null);transactionPageRequest(apiUrl,token,kind,c.signal,cursor,status).then(async page=>{if(c.signal.aborted)return;setRows(page.items);setNext(page.nextCursor);try{const groups=await Promise.all([catalogLookup(apiUrl,kind==='sales'?'customers':'suppliers',token,c.signal,page.items.map(row=>row.partnerId)),catalogLookup(apiUrl,'products',token,c.signal,page.items.map(row=>row.productId))]);if(!c.signal.aborted)setNames(Object.fromEntries(groups.flatMap((rows,index)=>rows.map(row=>[(index===0?'partner:':'product:')+row.id,row.name]))));}catch(e){if(!c.signal.aborted)setNameError(e instanceof Error?e.message:'No se pudieron consultar los nombres.');}}).catch(e=>{if(!c.signal.aborted)setError(e instanceof Error?e.message:'No se pudo consultar.');}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[apiUrl,token,kind,cursor,status,revision]);
 async function change(row:Transaction,target:string) {
  if(write.current||!canEdit||loading)return;
  if(!window.confirm(`Cambiar ${kind==='sales'?'venta':'compra'} de ${row.status} a ${target}. Importe: ${row.total}. Este cambio no registra automáticamente movimientos de inventario ni caja.`))return;
  const c=new AbortController();write.current=c;setSaving(true);setError('');setNotice('');
  try{await updateTransactionStatusRequest(apiUrl,token,kind,row,target,c.signal);if(c.signal.aborted)return;setNotice('Estado actualizado.');setCursors(['']);setRevision(v=>v+1);}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:'No se pudo confirmar el estado. Actualiza antes de reintentar.');}finally{write.current=null;if(!c.signal.aborted)setSaving(false);}
 }
 const statuses=kind==='sales'?['PENDIENTE','PAGADA','CANCELADA']:['PENDIENTE','APROBADA','RECIBIDA','CANCELADA'];const locked=loading||saving||!!settling;
 return <>{receipt&&<ReceiptView key={receipt.id} base={apiUrl} token={token} kind={kind} row={receipt} companyId={companyId} branchId={branchId} onClose={()=>setReceipt(null)}/>}{settling&&<SettlementForm key={settling.id} apiUrl={apiUrl} token={token} kind={kind} row={settling} companyId={companyId} branchId={branchId} onCancel={()=>setSettling(null)} onDone={id=>{setSettling(null);setNotice('Operación conjunta confirmada. Comprobante: '+id);setCursors(['']);setRevision(v=>v+1);}}/>}<section className="panel"><h3>{kind==='sales'?'Ventas registradas':'Órdenes de compra'}</h3><div className="field"><label htmlFor={kind+'-status'}>Estado</label><select id={kind+'-status'} value={status} disabled={saving||!!settling} onChange={e=>{setStatus(e.target.value);setCursors(['']);setNotice('');}}><option value="">Todos</option>{statuses.map(value=><option key={value}>{value}</option>)}</select></div>{loading&&<p>Consultando…</p>}{error&&<p role="alert" className="error-box">{error}</p>}{notice&&<p role="status">{notice}</p>}{nameError&&<p role="alert">Los registros siguen disponibles por identificador. {nameError}</p>}{!loading&&!error&&<><p>Página {cursors.length} · {rows.length} registros</p>{!rows.length&&<p>No hay registros para este estado.</p>}<div className="data-list">{rows.map(row=><div className="data-row" key={row.id}><span><strong>{row.status} · {row.total.toLocaleString('es-MX',{minimumFractionDigits:2})}</strong><small>{names['partner:'+row.partnerId]??row.partnerId} · {names['product:'+row.productId]??row.productId} · Cantidad: {row.quantity}</small><small>Registro: {row.id}</small></span>{<button disabled={saving||!!settling} onClick={()=>setReceipt(row)}>Ver comprobante</button>}{canEdit&&<div style={{display:'flex',gap:8}}>{((kind==='sales'&&row.status==='PENDIENTE')||(kind==='purchase-orders'&&row.status==='APROBADA'))&&row.total>0&&<button disabled={saving||!!settling} onClick={()=>setSettling(row)}>{kind==='sales'?'Cobrar y entregar':'Recibir y pagar'}</button>}{transactionStatusOptions(kind,row.status).map(target=><button key={target} disabled={saving||!!settling} onClick={()=>void change(row,target)}>{target==='PAGADA'?'Marcar pagada':target==='APROBADA'?'Aprobar':target==='RECIBIDA'?'Marcar recibida':'Cancelar registro'}</button>)}</div>}</div>)}</div></>}<div style={{display:'flex',gap:12,marginTop:16}}><button disabled={locked||cursors.length===1} onClick={()=>setCursors(v=>v.slice(0,-1))}>Anterior</button><button disabled={locked||!next} onClick={()=>{if(next)setCursors(v=>[...v,next]);}}>Siguiente</button><button disabled={locked} onClick={()=>{setCursors(['']);setRevision(v=>v+1);}}>{error?'Reintentar':'Actualizar'}</button></div></section></>;
}
