import {useEffect,useRef,useState} from 'react';import {ApiError} from './webApi';import {invoiceSales,createDraft,cancelDraft,type Invoice,type InvoiceSale} from './invoiceApi';
export function useInvoiceForm(base:string,token:string,co:string,br:string,onSaved:()=>void,original?:Invoice,onExpired?:()=>void){
 const [number,setNumber]=useState(''),[issueDate,setIssueDate]=useState(new Date().toISOString().slice(0,10)),[dueDate,setDueDate]=useState(new Date().toISOString().slice(0,10)),[taxRate,setTaxRate]=useState('0'),[reason,setReason]=useState(''),[sale,setSale]=useState<InvoiceSale|null>(null),[page,setPage]=useState<{items:InvoiceSale[];nextCursor:string|null}>({items:[],nextCursor:null}),[cursors,setCursors]=useState<Array<string|undefined>>([undefined]),[loading,setLoading]=useState(!original),[busy,setBusy]=useState(false),[blocked,setBlocked]=useState(false),[error,setError]=useState('');const lock=useRef(false),alive=useRef(true),write=useRef<AbortController|null>(null);const cursor=cursors[cursors.length-1];
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;write.current?.abort();};},[]);
 useEffect(()=>{if(original)return;const c=new AbortController();setLoading(true);setError('');invoiceSales(base,token,co,br,cursor,c.signal).then(p=>{if(!c.signal.aborted)setPage(p);}).catch(e=>{if(!c.signal.aborted){setPage({items:[],nextCursor:null});setError(e instanceof Error?e.message:'No se pudo consultar.');if(e instanceof ApiError&&e.status===401)onExpired?.();}}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[base,token,co,br,cursor,original,onExpired]);
 const ready=!busy&&!blocked&&(original?reason.trim().length>=3:!!sale&&!!number.trim()&&!!issueDate&&!!dueDate&&taxRate.trim()!==''&&Number.isFinite(Number(taxRate)));
 async function save(){if(!ready||lock.current)return;lock.current=true;setBusy(true);setError('');write.current=new AbortController();try{if(original)await cancelDraft(base,token,original,reason,write.current.signal);else await createDraft(base,token,sale!,{number,issueDate,dueDate,taxRate:Number(taxRate)},write.current.signal);if(alive.current)onSaved();}catch(e){if(alive.current){setBlocked(!(e instanceof ApiError&&e.status===400));setError(e instanceof Error?e.message:'Actualiza antes de reintentar.');if(e instanceof ApiError&&e.status===401)onExpired?.();}}finally{lock.current=false;write.current=null;if(alive.current)setBusy(false);}}
 return {number,setNumber,issueDate,setIssueDate,dueDate,setDueDate,taxRate,setTaxRate,reason,setReason,sale,setSale,page,loading,busy,blocked,error,ready,save,pageNumber:cursors.length,previous:()=>setCursors(v=>v.length>1?v.slice(0,-1):v),next:()=>{if(page.nextCursor)setCursors(v=>[...v,page.nextCursor!]);}};
}
