import mongoose from 'mongoose';import {z} from 'zod';import {AppError} from '../../errors/AppError.js';import {catalogFilter,catalogSlice} from '../../core/catalogPagination.js';import {getMaintenanceOrderModel} from './models/MaintenanceOrder.js';import {getAuditEventModel} from '../auditoria/models/AuditEvent.js';
const id=z.string().regex(/^[a-f0-9]{24}$/i);const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>{const d=new Date(v+'T00:00:00Z');return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===v;});
export const maintenanceCreateSchema=z.object({assetName:z.string().trim().min(2).max(120),description:z.string().trim().min(3).max(1000),scheduledDate:date,priority:z.enum(['low','medium','high'])}).strict();
export const maintenanceStateSchema=z.object({status:z.enum(['in_progress','completed','cancelled']),expectedStatus:z.enum(['scheduled','in_progress']),expectedUpdatedAt:z.string().datetime(),completionNote:z.string().trim().min(3).max(1000).optional()}).strict().refine(v=>(v.status==='cancelled'||v.expectedStatus==='scheduled'&&v.status==='in_progress'||v.expectedStatus==='in_progress'&&v.status==='completed')&&(v.status==='completed'?!!v.completionNote:v.completionNote===undefined));
const querySchema=z.object({search:z.string().trim().max(100).default(''),status:z.enum(['scheduled','in_progress','completed','cancelled']).optional(),cursor:id.optional(),limit:z.coerce.number().int().min(1).max(50).default(20)}).strict();
const invalid=()=>new AppError({code:'VALIDATION_ERROR',message:'Invalid maintenance order',friendlyMessage:'Revisa equipo, trabajo, fecha, prioridad y resultado del mantenimiento.',statusCode:400});
export function parseMaintenancePage(raw:unknown){const p=querySchema.safeParse(raw);if(!p.success)throw invalid();return p.data;}
type Scope={companyId:string;branchId:string;userId:string;ipAddress?:string};
export async function pageMaintenance(scope:Scope,q:ReturnType<typeof parseMaintenancePage>){const {status,...query}=q;const filter=catalogFilter({companyId:scope.companyId,branchId:scope.branchId},query,['assetName','description']);if(status)filter.status=status;return catalogSlice(await getMaintenanceOrderModel().find(filter).sort({_id:-1}).limit(q.limit+1).lean().exec(),q.limit);}
export async function maintenanceSummary(scope:Scope){const rows=await getMaintenanceOrderModel().aggregate([{$match:{companyId:scope.companyId,branchId:scope.branchId}},{$group:{_id:'$status',count:{$sum:1}}}]);const counts={scheduled:0,in_progress:0,completed:0,cancelled:0};for(const row of rows)if(row._id in counts)counts[row._id as keyof typeof counts]=row.count;return {counts,total:Object.values(counts).reduce((a,b)=>a+b,0)};}
export async function administerMaintenance(scope:Scope,payload:unknown,orderId?:string){const p=orderId?maintenanceStateSchema.safeParse(payload):maintenanceCreateSchema.safeParse(payload);if(!p.success||!scope.userId||orderId&&!id.safeParse(orderId).success)throw invalid();await Promise.all([getMaintenanceOrderModel().init(),getAuditEventModel().init()]);const session=await mongoose.startSession();let result;
try{await session.withTransaction(async()=>{let row;if(orderId){const input=p.data as z.infer<typeof maintenanceStateSchema>;row=await getMaintenanceOrderModel().findOneAndUpdate({_id:orderId,companyId:scope.companyId,branchId:scope.branchId,status:input.expectedStatus,updatedAt:new Date(input.expectedUpdatedAt)},{$set:{status:input.status,...(input.completionNote?{completionNote:input.completionNote}:{})}},{new:true,session}).lean().exec();if(!row)throw new AppError({code:'CONFLICT',message:'Maintenance changed',friendlyMessage:'La orden cambió o ya está cerrada. Actualiza antes de reintentar.',statusCode:409});}else{const [created]=await getMaintenanceOrderModel().create([{...p.data,companyId:scope.companyId,branchId:scope.branchId,status:'scheduled'}],{session});row=created.toObject();}await getAuditEventModel().create([{userId:scope.userId,companyId:scope.companyId,branchId:scope.branchId,action:orderId?'UPDATE':'CREATE',module:'mantenimiento',entityId:String(row._id),details:{status:row.status,assetName:row.assetName,completionNote:row.completionNote},ipAddress:scope.ipAddress}],{session});const {_id,...rest}=row;result={id:String(_id),...rest};});return result!;}finally{await session.endSession();}}
