import mongoose from 'mongoose';import {z} from 'zod';import {AppError} from '../../errors/AppError.js';import {catalogFilter,catalogSlice} from '../../core/catalogPagination.js';import {getOpportunityModel} from './models/Opportunity.js';import {getCustomerModel} from '../clientes/models/Customer.js';import {getAuditEventModel} from '../auditoria/models/AuditEvent.js';
const id=z.string().regex(/^[a-f0-9]{24}$/i);const stage=z.enum(['QUALIFICATION','PROPOSAL','NEGOTIATION','CLOSED_WON','CLOSED_LOST']);
export const opportunityCreateSchema=z.object({customerId:id,name:z.string().trim().min(2).max(120),amount:z.number().finite().min(0.01).max(1e12).refine(v=>Math.abs(v*100-Math.round(v*100))<0.000001)}).strict();
export const opportunityStageSchema=z.object({stage,expectedStage:stage,expectedUpdatedAt:z.string().datetime()}).strict();
const querySchema=z.object({search:z.string().trim().max(100).default(''),status:z.enum(['OPEN','WON','LOST']).optional(),cursor:id.optional(),limit:z.coerce.number().int().min(1).max(50).default(20)}).strict();
const invalid=()=>new AppError({code:'VALIDATION_ERROR',message:'Invalid CRM operation',friendlyMessage:'Revisa cliente, nombre, monto y etapa de la oportunidad.',statusCode:400});
export function parseOpportunityPage(raw:unknown){const p=querySchema.safeParse(raw);if(!p.success)throw invalid();return p.data;}
type Scope={companyId:string;branchId:string;userId:string;ipAddress?:string};
export async function pageOpportunities(scope:Scope,q:ReturnType<typeof parseOpportunityPage>){const {status,...query}=q;const filter=catalogFilter({companyId:scope.companyId,branchId:scope.branchId},query,['name']);if(status)filter.status=status;const rows=await getOpportunityModel().find(filter).sort({_id:-1}).limit(q.limit+1).lean().exec();const ids=rows.map(r=>r.customerId).filter(v=>/^[a-f0-9]{24}$/i.test(v));const customers=await getCustomerModel().find({companyId:scope.companyId,branchId:scope.branchId,_id:{$in:ids}}).select('name').lean().exec();const names=new Map(customers.map(c=>[String(c._id),c.name]));return catalogSlice(rows.map(r=>({...r,customerName:names.get(r.customerId)})),q.limit);}
export async function administerOpportunity(scope:Scope,payload:unknown,opportunityId?:string){const p=opportunityId?opportunityStageSchema.safeParse(payload):opportunityCreateSchema.safeParse(payload);if(!p.success||!scope.userId||opportunityId&&!id.safeParse(opportunityId).success)throw invalid();await Promise.all([getOpportunityModel().init(),getAuditEventModel().init()]);const session=await mongoose.startSession();let result;
try{await session.withTransaction(async()=>{let row;if(opportunityId){const input=p.data as z.infer<typeof opportunityStageSchema>;if(input.stage===input.expectedStage||['CLOSED_WON','CLOSED_LOST'].includes(input.expectedStage))throw invalid();const status=input.stage==='CLOSED_WON'?'WON':input.stage==='CLOSED_LOST'?'LOST':'OPEN';row=await getOpportunityModel().findOneAndUpdate({_id:opportunityId,companyId:scope.companyId,branchId:scope.branchId,status:'OPEN',stage:input.expectedStage,updatedAt:new Date(input.expectedUpdatedAt)},{$set:{stage:input.stage,status}},{new:true,session}).lean().exec();if(!row)throw new AppError({code:'CONFLICT',message:'Opportunity changed',friendlyMessage:'La oportunidad cambió o ya está cerrada. Actualiza antes de reintentar.',statusCode:409});}else{const input=p.data as z.infer<typeof opportunityCreateSchema>;if(!await getCustomerModel().exists({_id:input.customerId,companyId:scope.companyId,branchId:scope.branchId,status:'ACTIVE'}).session(session))throw invalid();const [created]=await getOpportunityModel().create([{...input,companyId:scope.companyId,branchId:scope.branchId,stage:'QUALIFICATION',status:'OPEN'}],{session});row=created.toObject();}await getAuditEventModel().create([{userId:scope.userId,companyId:scope.companyId,branchId:scope.branchId,action:opportunityId?'UPDATE':'CREATE',module:'crm',entityId:String(row._id),details:{stage:row.stage,status:row.status,amount:row.amount},ipAddress:scope.ipAddress}],{session});const {_id,...rest}=row;result={id:String(_id),...rest};});return result!;}finally{await session.endSession();}}
