import mongoose from 'mongoose';import {z} from 'zod';import {AppError} from '../../errors/AppError.js';import {catalogFilter,catalogSlice} from '../../core/catalogPagination.js';import {getQualityInspectionModel} from './models/QualityInspection.js';import {getAuditEventModel} from '../auditoria/models/AuditEvent.js';
const id=z.string().regex(/^[a-f0-9]{24}$/i);const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>{const d=new Date(v+'T00:00:00Z');return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===v;});
export const qualityCreateSchema=z.object({subject:z.string().trim().min(2).max(120),criteria:z.string().trim().min(3).max(1000),inspectionDate:date,priority:z.enum(['low','medium','high'])}).strict();
export const qualityStateSchema=z.object({status:z.enum(['in_progress','completed','cancelled']),expectedStatus:z.enum(['scheduled','in_progress']),expectedUpdatedAt:z.string().datetime(),result:z.enum(['pass','watch','fail']).optional(),completionNote:z.string().trim().min(3).max(1000).optional()}).strict().refine(v=>(v.status==='cancelled'||v.expectedStatus==='scheduled'&&v.status==='in_progress'||v.expectedStatus==='in_progress'&&v.status==='completed')&&(v.status==='completed'?!!v.completionNote&&!!v.result:v.completionNote===undefined&&v.result===undefined));
const querySchema=z.object({search:z.string().trim().max(100).default(''),status:z.enum(['scheduled','in_progress','completed','cancelled']).optional(),cursor:id.optional(),limit:z.coerce.number().int().min(1).max(50).default(20)}).strict();
const invalid=()=>new AppError({code:'VALIDATION_ERROR',message:'Invalid quality order',friendlyMessage:'Revisa objeto, criterios, fecha, prioridad y resultado de la inspección.',statusCode:400});
export function parseQualityPage(raw:unknown){const p=querySchema.safeParse(raw);if(!p.success)throw invalid();return p.data;}
type Scope={companyId:string;branchId:string;userId:string;ipAddress?:string};
export async function pageQuality(scope:Scope,q:ReturnType<typeof parseQualityPage>){const {status,...query}=q;const filter=catalogFilter({companyId:scope.companyId,branchId:scope.branchId},query,['subject','criteria']);if(status)filter.status=status;return catalogSlice(await getQualityInspectionModel().find(filter).sort({_id:-1}).limit(q.limit+1).lean().exec(),q.limit);}
export async function qualitySummary(scope:Scope){const rows=await getQualityInspectionModel().aggregate([{$match:{companyId:scope.companyId,branchId:scope.branchId}},{$group:{_id:'$status',count:{$sum:1}}}]);const counts={scheduled:0,in_progress:0,completed:0,cancelled:0};for(const row of rows)if(row._id in counts)counts[row._id as keyof typeof counts]=row.count;return {counts,total:Object.values(counts).reduce((a,b)=>a+b,0)};}
export async function administerQuality(scope:Scope,payload:unknown,orderId?:string){const p=orderId?qualityStateSchema.safeParse(payload):qualityCreateSchema.safeParse(payload);if(!p.success||!scope.userId||orderId&&!id.safeParse(orderId).success)throw invalid();await Promise.all([getQualityInspectionModel().init(),getAuditEventModel().init()]);const session=await mongoose.startSession();let result;
try{await session.withTransaction(async()=>{let row;if(orderId){const input=p.data as z.infer<typeof qualityStateSchema>;row=await getQualityInspectionModel().findOneAndUpdate({_id:orderId,companyId:scope.companyId,branchId:scope.branchId,status:input.expectedStatus,updatedAt:new Date(input.expectedUpdatedAt)},{$set:{status:input.status,...(input.completionNote?{completionNote:input.completionNote,result:input.result}:{})}},{new:true,session}).lean().exec();if(!row)throw new AppError({code:'CONFLICT',message:'Quality changed',friendlyMessage:'La inspección cambió o ya está cerrada. Actualiza antes de reintentar.',statusCode:409});}else{const [created]=await getQualityInspectionModel().create([{...p.data,companyId:scope.companyId,branchId:scope.branchId,status:'scheduled'}],{session});row=created.toObject();}await getAuditEventModel().create([{userId:scope.userId,companyId:scope.companyId,branchId:scope.branchId,action:orderId?'UPDATE':'CREATE',module:'calidad',entityId:String(row._id),details:{status:row.status,subject:row.subject,completionNote:row.completionNote,result:row.result},ipAddress:scope.ipAddress}],{session});const {_id,...rest}=row;result={id:String(_id),...rest};});return result!;}finally{await session.endSession();}}
