import {test} from 'node:test';import assert from 'node:assert/strict';import {write,read,utils} from 'xlsx';import {projectDocument,productionDocument} from '../src/operationsDocument';import {documentWorkbook} from '../src/exportWorkbook';import {documentHtml} from '../src/exportDocument';
test('operation exports preserve numeric progress and production quantities in Excel and escape PDF content',()=>{
 const project={id:'project',companyId:'co',branchId:'br',customerId:'customer',customerName:'Client <script>',name:'Project & test',startDate:'2026-10-05',endDate:'2026-10-20',status:'PAUSED' as const,progress:42.5};
 const order={id:'order',companyId:'co',branchId:'br',productId:'product',productName:'Product <img>',productSku:'SKU-1',status:'completed' as const,plannedQuantity:1.25,completedQuantity:1.25,completionWarehouseName:'Warehouse',completionMovementId:'movement'};
 for(const doc of [projectDocument(project),productionDocument(order)]){const bytes=write(documentWorkbook(doc),{type:'array',bookType:'xlsx'});const workbook=read(bytes,{type:'array'});const rows=utils.sheet_to_json(workbook.Sheets[workbook.SheetNames[0]],{header:1}) as unknown[][];assert.ok(rows.length>0);const info=utils.sheet_to_json(workbook.Sheets['Información'],{header:1}) as unknown[][];assert.ok(info.flat().includes(doc.title));assert.ok(info.flat().includes(doc.note));assert.deepEqual(rows[1],doc.rows[0]);assert.match(documentHtml(doc),/&lt;/);assert.doesNotMatch(documentHtml(doc),/<script>|<img>/);}
 const projectSheet=documentWorkbook(projectDocument(project));assert.ok(Object.values(projectSheet.Sheets[projectSheet.SheetNames[0]]).some((cell:any)=>cell?.t==='n'&&cell.v===42.5));
 const orderSheet=documentWorkbook(productionDocument(order));assert.ok(Object.values(orderSheet.Sheets[orderSheet.SheetNames[0]]).some((cell:any)=>cell?.t==='n'&&cell.v===1.25));assert.match(productionDocument(order).note,/Incluye insumos/);
});

test('production material exports retain numeric consumption and escape names',()=>{const doc=productionDocument({id:'order',companyId:'co',branchId:'br',productId:'finished',plannedQuantity:2,completedQuantity:2,status:'completed',materials:[{productId:'material',warehouseId:'warehouse',quantity:0.25,movementId:'issue',productName:'Material <script>',warehouseName:'Origin'}]});assert.equal(doc.rows[1][3],0.25);assert.equal(doc.rows[1][4],0.25);assert.equal(doc.rows[1][6],'issue');assert.match(documentHtml(doc),/&lt;script&gt;/);assert.doesNotMatch(documentHtml(doc),/<script>/);const sheet=documentWorkbook(doc);assert.ok(Object.values(sheet.Sheets[sheet.SheetNames[0]]).some((cell:any)=>cell?.t==='n'&&cell.v===0.25));});

test('partial production report distinguishes consumed quantities and reported delivery costs',()=>{const doc=productionDocument({id:'order',companyId:'co',branchId:'br',productId:'finished',plannedQuantity:3,completedQuantity:1,status:'running',costCurrency:'MXN',productionCost:0.1,materials:[{productId:'raw',warehouseId:'origin',quantity:1,consumedQuantity:0.333333,movementId:'issue'}],deliveries:[{quantity:1,warehouseId:'target',warehouseName:'Target',movementId:'receipt',materials:[],cost:0.1}]});assert.equal(doc.rows[1][4],0.333333);assert.equal(doc.rows[2][7],0.1);assert.equal(doc.rows[2][8],'MXN');assert.equal(doc.rows[2][5],'Target');const sheet=documentWorkbook(doc);assert.ok(Object.values(sheet.Sheets[sheet.SheetNames[0]]).some((cell:any)=>cell?.t==='n'&&cell.v===0.1));});
