import mongoose from 'mongoose';import {z} from 'zod';import {AppError} from '../../errors/AppError.js';import {catalogFilter,catalogSlice} from '../../core/catalogPagination.js';import {getComplianceControlModel} from './models/ComplianceControl.js';import {getAuditEventModel} from '../auditoria/models/AuditEvent.js';
const id=z.string().regex(/^[a-f0-9]{24}$/i);const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>{const d=new Date(v+'T00:00:00Z');return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===v;});
export const complianceCreateSchema=z.object({name:z.string().trim().min(2).max(120),requirement:z.string().trim().min(3).max(1000),dueDate:date,priority:z.enum(['low','medium','high'])}).strict();
export const complianceStateSchema=z.object({status:z.enum(['reviewing','completed','cancelled']),expectedStatus:z.enum(['pending','reviewing']),expectedUpdatedAt:z.string().datetime(),result:z.enum(['pass','watch','fail']).optional(),evidenceNote:z.string().trim().min(3).max(1000).optional()}).strict().refine(v=>(v.status==='cancelled'||v.expectedStatus==='pending'&&v.status==='reviewing'||v.expectedStatus==='reviewing'&&v.status==='completed')&&(v.status==='completed'?!!v.evidenceNote&&!!v.result:v.evidenceNote===undefined&&v.result===undefined));
const querySchema=z.object({search:z.string().trim().max(100).default(''),status:z.enum(['pending','reviewing','completed','cancelled']).optional(),cursor:id.optional(),limit:z.coerce.number().int().min(1).max(50).default(20)}).strict();
const invalid=()=>new AppError({code:'VALIDATION_ERROR',message:'Invalid compliance order',friendlyMessage:'Revisa obligación, requisito, fecha límite, prioridad y evidencia.',statusCode:400});
export function parseCompliancePage(raw:unknown){const p=querySchema.safeParse(raw);if(!p.success)throw invalid();return p.data;}
type Scope={companyId:string;branchId:string;userId:string;ipAddress?:string};
export async function pageCompliance(scope:Scope,q:ReturnType<typeof parseCompliancePage>){const {status,...query}=q;const filter=catalogFilter({companyId:scope.companyId,branchId:scope.branchId},query,['name','requirement']);if(status)filter.status=status;return catalogSlice(await getComplianceControlModel().find(filter).sort({_id:-1}).limit(q.limit+1).lean().exec(),q.limit);}
export async function complianceSummary(scope:Scope){const rows=await getComplianceControlModel().aggregate([{$match:{companyId:scope.companyId,branchId:scope.branchId}},{$group:{_id:'$status',count:{$sum:1}}}]);const counts={pending:0,reviewing:0,completed:0,cancelled:0};for(const row of rows)if(row._id in counts)counts[row._id as keyof typeof counts]=row.count;return {counts,total:Object.values(counts).reduce((a,b)=>a+b,0)};}
export async function administerCompliance(scope:Scope,payload:unknown,orderId?:string){const p=orderId?complianceStateSchema.safeParse(payload):complianceCreateSchema.safeParse(payload);if(!p.success||!scope.userId||orderId&&!id.safeParse(orderId).success)throw invalid();await Promise.all([getComplianceControlModel().init(),getAuditEventModel().init()]);const session=await mongoose.startSession();let result;
try{await session.withTransaction(async()=>{let row;if(orderId){const input=p.data as z.infer<typeof complianceStateSchema>;row=await getComplianceControlModel().findOneAndUpdate({_id:orderId,companyId:scope.companyId,branchId:scope.branchId,status:input.expectedStatus,updatedAt:new Date(input.expectedUpdatedAt)},{$set:{status:input.status,...(input.evidenceNote?{evidenceNote:input.evidenceNote,result:input.result}:{})}},{new:true,session}).lean().exec();if(!row)throw new AppError({code:'CONFLICT',message:'Quality changed',friendlyMessage:'La obligación cambió o ya está cerrada. Actualiza antes de reintentar.',statusCode:409});}else{const [created]=await getComplianceControlModel().create([{...p.data,companyId:scope.companyId,branchId:scope.branchId,status:'pending'}],{session});row=created.toObject();}await getAuditEventModel().create([{userId:scope.userId,companyId:scope.companyId,branchId:scope.branchId,action:orderId?'UPDATE':'CREATE',module:'cumplimiento',entityId:String(row._id),details:{status:row.status,name:row.name,evidenceNote:row.evidenceNote,result:row.result},ipAddress:scope.ipAddress}],{session});const {_id,...rest}=row;result={id:String(_id),...rest};});return result!;}finally{await session.endSession();}}
